const test=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const domain=require('../web/domain.js');
function setup(){
 const listeners={},s={group:{id:'g'},events:[],tasks:[],people:[],attendance:{},venues:[],settings:{reminders:[]}};let seq=0;
 const c={D:domain,state:s,ctx:{busy:false},ui:{calendarYear:2026,calendarMonth:8,showExec:false},DEMO_TODAY:'2026-09-06',window:{addEventListener:(type,fn)=>(listeners[type]||=[]).push(fn)},document:{querySelector:()=>null},setTimeout,clearTimeout,Date,Set,FormData:class{constructor(f){this.values=f.values}get(n){return this.values[n]?.[0]??null}getAll(n){return this.values[n]||[]}},edit:()=>true,event:id=>s.events.find(e=>e.id===id),UID:()=>`e${++seq}`,clone:x=>structuredClone(x),checkpoint:()=>{},persist:()=>{},closeModal:()=>{},render:()=>{},actHandled:()=>{},toast:()=>{}};
 vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(__dirname,'../web/calendar.js'),'utf8'),c);
 function submit(values,{id='',mode='single',form='cal-event'}={}){const error={textContent:''},f={dataset:{form,id,mode},values:Object.fromEntries(Object.entries(values).map(([k,v])=>[k,Array.isArray(v)?v:[v]])),querySelector:()=>error};listeners.submit[0]({target:f});return error.textContent;}
 return {c,s,submit,listeners};
}
const basic={title:'練習',date:'2026-09-07',kind:'club',colorId:'blue'};
test('multi-date entry preserves existing same-day records and attendance',()=>{const {s,submit}=setup();s.events.push({id:'existing',...basic});s.attendance['existing|m']='manual';assert.equal(submit({...basic,selectedDate:['2026-09-08','2026-09-07','2026-09-08']},{mode:'multiple'}),'');assert.equal(s.events.length,3);assert.equal(s.events[1].date,'2026-09-07');assert.equal(s.events[1].seriesId,s.events[2].seriesId);assert.equal(s.events[2].colorId,'blue');assert.equal(s.attendance['existing|m'],'manual');});
test('period and weekly entry retain their distinct date semantics',()=>{const {s,submit}=setup();assert.equal(submit({...basic,endDate:'2026-09-10'},{mode:'period'}),'');assert.equal(s.events.length,1);assert.equal(s.events[0].endDate,'2026-09-10');assert.equal(submit({...basic,repeatUntil:'2026-09-30',weekday:['1','3']},{mode:'weekly'}),'');assert.equal(s.events.length,9);assert.ok(s.events.slice(1).every(e=>e.date===e.endDate));});
test('invalid date range and time are atomic',()=>{const {s,submit}=setup();assert.match(submit({...basic,endDate:'2026-09-01'},{mode:'period'}),/終了日/);assert.match(submit({...basic,start:'20:00',end:'19:00'}),/時刻/);assert.equal(s.events.length,0);});
test('series edit preserves dates and ids; single edit detaches only that record',()=>{const {s,submit}=setup();submit({...basic,selectedDate:['2026-09-07','2026-09-09']},{mode:'multiple'});const [a,b]=s.events,ids=s.events.map(e=>e.id);assert.equal(submit({...basic,title:'大会',scope:'series'},{id:a.id}),'');assert.deepEqual(s.events.map(e=>e.id),ids);assert.equal(b.date,'2026-09-09');assert.equal(b.title,'大会');submit({...basic,title:'この日だけ',scope:'single'},{id:a.id});assert.equal(a.seriesId,null);assert.equal(b.title,'大会');});
test('read-only members and in-flight saves cannot mutate calendar',()=>{const {c,s,submit}=setup();c.edit=()=>false;assert.match(submit(basic),/編集権限/);c.edit=()=>true;c.ctx.busy=true;submit(basic);assert.equal(s.events.length,0);});

test('simple club edit retains hidden legacy fields and only changes intended fields',()=>{const {s,submit}=setup();s.events.push({id:'old',...basic,start:'19:00',end:'21:00',venueId:'v',courts:3,notifications:['P7D'],memo:'前'});submit({...basic,title:'更新',memo:'後'},{id:'old'});assert.equal(s.events[0].start,'19:00');assert.equal(s.events[0].venueId,'v');assert.equal(s.events[0].courts,3);assert.deepEqual(s.events[0].notifications,['P7D']);assert.equal(s.events[0].memo,'後');});
test('multiple same-time executive records coexist without task copies',()=>{const {s,submit}=setup();for(const title of ['幹部会','準備'])assert.equal(submit({...basic,title,kind:'executive',start:'18:00',end:'19:00',assignee:['u1','u2'],notify:['P1M','P3D']}),'');assert.equal(s.events.length,2);assert.equal(s.tasks.length,0);assert.deepEqual(s.events[0].assignees,['u1','u2']);assert.deepEqual(s.events[0].notifications,['P1M','P3D']);});

test('showing executive schedules keeps club events and multiple overlapping executive events',()=>{const {c,s}=setup();s.events.push({id:'club',...basic},{id:'ex1',...basic,kind:'executive',title:'幹部会',start:'18:00'},{id:'ex2',...basic,kind:'executive',title:'準備',start:'18:00'});assert.equal(vm.runInContext("calItems('2026-09-07').length",c),1);c.ui.showExec=true;const ids=vm.runInContext("calItems('2026-09-07').map(x=>x.id)",c);assert.deepEqual(Array.from(ids),['club','ex1','ex2']);assert.equal(s.events.length,3);});

test('a day with one club event still offers adding an executive event',()=>{const {c,s,listeners}=setup();s.events.push({id:'club',...basic});c.ui.showExec=true;let content='',edits=0;c.modal=(_,html)=>content=html;c.jpDate=x=>x;c.esc=x=>x;c.action=(_,label)=>label;c.calEditor=()=>edits++;listeners.click[0]({target:{closest:()=>({disabled:false,dataset:{act:'cal-day',date:'2026-09-07'}})}});assert.equal(edits,0);assert.match(content,/練習/);assert.match(content,/幹部予定を追加/);assert.equal(s.events.length,1);});

test('dragging a period shifts its dates without changing IDs, attendance, gym or practice',async()=>{const {c,s}=setup();s.events=[{id:'e',...basic,endDate:'2026-09-09',seriesId:'series',memo:'保持'}];s.attendance={'e|m':false};s.venueAssignments={e:{venueId:'v'}};s.training={sheets:[{id:'sheet',eventId:'e'}]};c.wfSave=async fn=>fn();c.lockedPlan=()=>false;await c.calMoveRecord('event','e','2026-09-08','2026-09-11');assert.equal(s.events[0].date,'2026-09-10');assert.equal(s.events[0].endDate,'2026-09-12');assert.equal(s.events[0].seriesId,null);assert.equal(s.events[0].memo,'保持');assert.equal(s.attendance['e|m'],false);assert.equal(s.venueAssignments.e.venueId,'v');assert.equal(s.training.sheets[0].eventId,'e');});
test('dragging one executive schedule to an occupied day adds no duplicate task',async()=>{const {c,s}=setup();s.events=[{id:'a',...basic,kind:'executive'},{id:'b',...basic,kind:'executive',date:'2026-09-08'}];c.wfSave=async fn=>fn();await c.calMoveRecord('event','a','2026-09-07','2026-09-08');assert.equal(s.events.length,2);assert.equal(s.tasks.length,0);assert.equal(s.events[0].date,s.events[1].date);});
test('task drag preserves deadline time; read-only and locked schedules cannot move',async()=>{const {c,s}=setup();s.tasks=[{id:'t',title:'提出',date:'2026-09-07',time:'18:30'}];c.wfSave=async fn=>fn();await c.calMoveRecord('task','t','2026-09-07','2026-09-09');assert.equal(s.tasks[0].time,'18:30');assert.equal(s.tasks[0].date,'2026-09-09');c.edit=()=>false;await assert.rejects(c.calMoveRecord('task','t','2026-09-09','2026-09-10'),/権限/);c.edit=()=>true;s.events=[{id:'e',...basic}];s.plans=[{id:'p',eventId:'e'}];c.lockedPlan=()=>true;await assert.rejects(c.calMoveRecord('event','e','2026-09-07','2026-09-09'),/精算確定/);assert.equal(s.events[0].date,'2026-09-07');});
test('moving a planned practice shifts default trip dates and retains allocation',async()=>{const {c,s}=setup();s.events=[{id:'e',...basic}];const legs={outbound:[{driver:'m',riders:[]}],return:[{driver:'m',riders:[]}]};s.plans=[{id:'p',eventId:'e',status:'registered',legDates:{outbound:'2026-09-07',return:'2026-09-07'},legs}];c.wfSave=async fn=>fn();c.lockedPlan=()=>false;await c.calMoveRecord('event','e','2026-09-07','2026-09-08');assert.equal(s.plans[0].legDates.outbound,'2026-09-08');assert.equal(s.plans[0].status,'draft');assert.equal(s.plans[0].legs,legs);});

test('calendar hold separates scrolling, long-press move and cancellation',async()=>{const {c,s,listeners}=setup();s.events=[{id:'e',...basic}];let timer=null,moves=0;const day={dataset:{date:'2026-09-07'},setPointerCapture:()=>{},classList:{add:()=>{}}},dest={dataset:{date:'2026-09-08'},classList:{add:()=>{}}};c.setTimeout=fn=>{timer=fn;return 1};c.clearTimeout=()=>{timer=null};c.document={querySelectorAll:()=>[],createElement:()=>({style:{},remove:()=>{}}),body:{appendChild:()=>{}},elementFromPoint:()=>({closest:()=>dest})};c.calMoveRecord=async()=>moves++;const ev=(x=10)=>({target:{closest:q=>q.includes('data-act')?day:null},button:0,pointerId:1,clientX:x,clientY:10,preventDefault:()=>{}});listeners.pointerdown[0](ev());listeners.pointermove[0](ev(40));assert.equal(timer,null);await listeners.pointerup[0](ev(40));assert.equal(moves,0);listeners.pointerdown[0](ev());timer();listeners.pointermove[0](ev(40));await listeners.pointerup[0](ev(40));assert.equal(moves,1);listeners.pointerdown[0](ev());timer();await listeners.pointercancel[0](ev(40));assert.equal(moves,1);});
