// Local synthetic state only. All page network requests are blocked.
import {spawn} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {join,resolve} from 'node:path';
import assert from 'node:assert/strict';
const chrome=process.argv[2];if(!chrome)throw Error('Pass a local Chromium executable path');
const profile=resolve(process.argv[3]||'../carpool-browser-profile'),out=resolve('../carpool-qa');mkdirSync(out,{recursive:true});
const browser=spawn(chrome,['--headless','--disable-gpu','--no-sandbox','--disable-background-networking','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{windowsHide:true,stdio:['ignore','ignore','pipe']});
let ws,sequence=0;const pending=new Map(),errors=[];
try{
 const url=await new Promise((yes,no)=>{let log='';const timer=setTimeout(()=>no(Error('Chromium startup timeout: '+log.slice(-1000))),15000);browser.stderr.on('data',data=>{log+=data.toString();const match=log.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(match){clearTimeout(timer);yes(match[1]);}});browser.on('exit',code=>{clearTimeout(timer);no(Error('Chromium exited '+code));});});
 ws=new WebSocket(url);await new Promise((yes,no)=>{ws.addEventListener('open',yes,{once:true});ws.addEventListener('error',no,{once:true});});
 ws.addEventListener('message',event=>{const msg=JSON.parse(event.data);if(msg.id){const p=pending.get(msg.id);if(p){pending.delete(msg.id);msg.error?p.no(Error(JSON.stringify(msg.error))):p.yes(msg.result);}}else if(msg.method==='Runtime.exceptionThrown')errors.push(msg.params.exceptionDetails);});
 const call=(method,params={},sessionId)=>new Promise((yes,no)=>{const id=++sequence;pending.set(id,{yes,no});ws.send(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{})}));});
 const {targetId}=await call('Target.createTarget',{url:'about:blank'}),{sessionId}=await call('Target.attachToTarget',{targetId,flatten:true});
 const page=(method,params={})=>call(method,params,sessionId);
 await page('Page.enable');await page('Runtime.enable');await page('Network.enable');await page('Network.setBlockedURLs',{urls:['*']});await page('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await page('Page.setInterceptFileChooserDialog',{enabled:true});
 await call('Browser.setDownloadBehavior',{behavior:'deny'});
 const {frameTree}=await page('Page.getFrameTree');
 const shim=`<script>for(const name of ['localStorage','sessionStorage']){const data={};Object.defineProperty(window,name,{value:{getItem:k=>data[k]??null,setItem:(k,v)=>data[k]=String(v),removeItem:k=>delete data[k]}})};window.fetch=async()=>{throw Error('Network blocked in local QA')};window.confirm=()=>true;</script>`;
 const html=readFileSync('club-demo.html','utf8').replace('<body>','<body>'+shim);
 await page('Page.setDocumentContent',{frameId:frameTree.frame.id,html});
 const run=async expression=>{const value=await page('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(value.exceptionDetails)throw Error(JSON.stringify(value.exceptionDetails));return value.result.value;};
 await run('new Promise(resolve=>setTimeout(resolve,150))');
 assert.equal(await run('ctx.ready'),true);
 const make=`(()=>{const s=demoSeed();s.events=[{id:'ev',kind:'club',title:'練習',date:'2026-09-02',venueId:'v1'}];s.people=['u','s','a','b'].map(id=>({id,name:id,grade:3,seniority:'below',pickup:id==='s'?'station':'university',active:true}));s.attendance=Object.fromEntries(s.people.map(m=>['ev|'+m.id,true]));s.plans=[{id:'p',eventId:'ev',status:'registered',fareMode:'fixed',linked:true,enabled:{outbound:true,return:true},need:{outbound:{},return:{}},legs:{outbound:[{id:'cu',pickup:'university',driver:'u',riders:['a']},{id:'cs',pickup:'station',driver:'s',riders:['b']}],return:[{id:'cu',pickup:'university',driver:'u',riders:['a']},{id:'cs',pickup:'station',driver:'s',riders:['b']}]},unitYen:300,unitYenOverride:400,version:1,collections:{}}];s.settlements=[];state=s;ctx.mode='demo';ui.settlementMonth='2026-09';location.hash='settlement';render();})()`;
 await run(make);assert.equal(await run('document.querySelectorAll(\'[data-act="charge-edit"]\').length'),4);
 assert.equal(await run('D.normalSettlement(state,"2026-09").paidAmount'),0);
 await run('document.querySelector(\'[data-act="charge-edit"][data-rider="a"][data-leg="outbound"]\').click()');
 assert.equal(await run('document.querySelector(\'[name="collectedAmount"]\').value'),'50');
 await run('document.querySelector(\'[name="collected"]\').checked=true;document.querySelector(\'[name="collectedAmount"]\').value="49";document.querySelector(\'form[data-form="charge"] button\').click()');
 assert.deepEqual(await run('state.plans[0].collections["outbound|a"]'),{status:'collected',amount:49});
 assert.deepEqual(await run('D.normalSettlement(state,"2026-09").days[0].payouts.map(x=>x.amount)'),[29,20]);
 assert.equal(await run('state.plans[0].unitYenOverride'),400);
 await run('render();document.querySelector(\'[data-act="charge-edit"][data-rider="a"][data-leg="outbound"]\').click()');
 assert.equal(await run('document.querySelector(\'[name="collectedAmount"]\').value'),'49');
 await run('closeModal();document.querySelector(\'[data-act="statement-lock"]\').click()');
 assert.equal(await run('state.settlements[0].normal.collectedAmount'),49);
 assert.equal(await run('state.settlements[0].normal.paidAmount'),49);
 assert.equal(await run('state.settlements[0].planIds.includes("p")'),true);
 assert.equal(await run('document.querySelector(\'[data-act="charge-edit"]\').disabled'),true);
 const old=await run('JSON.stringify(state.settlements)');await run('state.settings.carpoolFees.station=12345;render()');assert.equal(await run('JSON.stringify(state.settlements)'),old);
 await run('state.settlements=[{id:"old",month:"2026-09",locked:true,planIds:["p"],lines:[{rider:"a",driver:"u",amount:600,count:2,riderName:"旧乗車者",driverName:"旧運転者",details:[{date:"2026-09-02",leg:"outbound",count:2,unitYen:300,amount:600}]}]}];render()');
 assert.equal(await run('document.querySelector("#app").innerText.includes("¥600")||document.querySelector("#app").innerText.includes("600円")'),true);
 assert.equal(await run('document.querySelectorAll(\'[data-act="charge-edit"]\').length'),0);
 assert.equal(await run('document.querySelector("#app").innerText.includes("旧乗車者")'),true);
 await run(make);await run('carOptions("p")');assert.equal(await run('document.querySelector(\'[name="fareMode"] option[value="event"]\').textContent'),'イベント配車');assert.equal(await run('document.querySelector(\'[name="unitYen"]\')'),null);
 await run('closeModal();state.events.push({id:"trip",kind:"club",title:"イベント",date:"2026-09-02"});const p=structuredClone(state.plans[0]);p.id="trip-plan";p.eventId="trip";p.fareMode="event";p.legs.outbound=[{id:"trip-car",driver:"u",pickup:"university",riders:["a","b","s"]}];p.legs.return=structuredClone(p.legs.outbound);p.eventCosts={outbound:{"trip-car":{gasoline:4000,toll:7000,parking:1050}},return:{}};state.plans.push(p);render()');
 const oldEvent=await run('JSON.stringify(state.plans[1])');await run('document.querySelector(\'[data-act="settlement-detail2"][data-rider="a"][data-driver="u"]\').click()');
 assert.equal(await run('document.querySelector(".modal").innerText.includes("12,050")'),true);assert.equal(await run('JSON.stringify(state.plans[1])'),oldEvent);
 await run('closeModal();state.plans=state.plans.filter(p=>p.id!=="trip-plan");state.plans[0].collections={"outbound|a":{status:"collected",amount:49}};render()');
 const screenshot=await page('Page.captureScreenshot',{captureBeyondViewport:true});writeFileSync(join(out,'settlement-390.png'),Buffer.from(screenshot.data,'base64'));
 assert.equal(await run('document.documentElement.scrollWidth<=390'),true);
 assert.equal(errors.length,0,JSON.stringify(errors));
 writeFileSync(join(out,'browser-result.json'),JSON.stringify({pass:true,scenarios:['demo boots','roundtrip collection form','49 yen recalculation and reload','new statement lock preserves totals','old snapshot preserves amounts and names','event settings and expense detail retained','390px layout'],errors,limits:'Synthetic in-memory storage; page network blocked. Chromium DOM/forms only; no real accounting data or authentication.'},null,2));
 console.log('PASS: local Chromium settlement forms, recalculation, snapshot protection, event selector and mobile layout');
 await call('Browser.close');
}finally{ws?.close();browser.kill();}
