import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,validate,updateState,seedAttendance,today,targeted} from '../supabase/functions/club-api/domain.mjs';
import {exchangeLine} from '../supabase/functions/club-api/line.mjs';
const owner={id:'owner',name:'オーナー'},viewer={id:'viewer',name:'閲覧者'},ops=new Set(['owner','viewer']);
function populated(){const s=emptyState('g','部活');s.people=Array.from({length:4},(_,i)=>({id:'m'+i,name:'部員'+i,grade:3,seniority:'below',pickup:'university',active:true,defaultOverride:null}));s.events=[{id:'e',title:'練習',kind:'club',date:today(),start:'19:00',end:'21:00',assignees:[]}];seedAttendance(s);return s;}
function plan(){const cars=[{id:'c',pickup:'university',driver:'m0',riders:['m1','m2','m3']}];return {id:'p',eventId:'e',linked:true,enabled:{outbound:true,return:true},need:{outbound:{},return:{}},legs:{outbound:cars,return:structuredClone(cars)},unitYen:300,status:'draft'};}
const update=(s,c,u=owner)=>updateState(s,c,u,'owner','g',ops);
test('valid state, attendance defaults and manual values',()=>{const s=populated();validate(s,ops);assert.equal(s.attendance['e|m0'],true);s.attendance['e|m0']=false;seedAttendance(s);assert.equal(s.attendance['e|m0'],false);});
test('attendance month-end horizon and far dates',()=>{const s=populated();s.attendance={};s.events[0].date='2026-05-01';seedAttendance(s,'2026-01-31');assert.deepEqual(s.attendance,{});s.events[0].date='2026-04-30';seedAttendance(s,'2026-01-31');assert.equal(s.attendance['e|m0'],true);});
test('owner and module assignment required; owner cannot be supplied',()=>{const s=populated();assert.throws(()=>update(s,{people:[]},viewer),e=>e.status===403);assert.throws(()=>update(s,{roles:{}},viewer),e=>e.status===403);assert.throws(()=>update(s,{ownerId:'viewer'}));assert.throws(()=>update(s,{group:{id:'other',name:'x'}}),e=>e.status===403);s.roles['備品']=['viewer'];assert.equal(update(s,{equipment:[{id:'q',name:'ボール',quantity:2,unit:'個',threshold:null}]},viewer).equipment.length,1);});
test('malformed arrays, nested fields and dates rejected',()=>{for(const c of [{people:null},{roles:[]},{attendance:null},{plans:[{id:'p'}]},{events:[{id:'e',title:'x',kind:'club',date:'2026-02-30'}]}])assert.throws(()=>update(populated(),c),e=>e.status===400);});
test('foreign assignees and duplicate identifiers rejected',()=>{const s=populated();assert.throws(()=>update(s,{roles:{予定:['outsider']}}));assert.throws(()=>update(s,{people:[...s.people,s.people[0]]}));});
test('task assignee may only complete; completion identity is server owned',()=>{const s=populated();s.tasks=[{id:'t',title:'準備',date:today(),time:'19:00',assignees:['viewer'],done:false}];let tasks=structuredClone(s.tasks);tasks[0].done=true;tasks[0].completedBy='spoof';assert.equal(update(s,{tasks},viewer).tasks[0].completedBy,'viewer');tasks[0].title='変更';assert.throws(()=>update(s,{tasks},viewer),e=>e.status===403);s.tasks[0].assignmentNeedsReview=true;tasks=structuredClone(s.tasks);tasks[0].done=true;assert.throws(()=>update(s,{tasks},viewer),e=>e.status===403);});
test('hidden targeted notices preserved and cannot be overwritten',()=>{const s=populated();s.roles['お知らせ']=['viewer'];s.notices=[{id:'hidden',title:'内密',body:'本文',assignees:['owner']},{id:'visible',title:'全体',body:'本文',assignees:[]}];assert.equal(targeted(s,s.notices[0],'viewer'),false);const n={...s.notices[1],body:'変更'};assert.equal(update(s,{notices:[n]},viewer).notices.length,2);assert.throws(()=>update(s,{notices:[...s.notices]},viewer),e=>e.status===403);});
test('car registration validates attendance, capacity, uniqueness and mirror',()=>{const s=populated(),p=plan();p.status='registered';assert.equal(update(s,{plans:[p]}).plans[0].status,'registered');s.attendance['e|m0']=false;assert.throws(()=>update(s,{plans:[p]}));for(const mutate of [p=>delete p.enabled,p=>p.legs.outbound[0].riders.push('m2'),p=>p.legs.outbound[0].riders.splice(0,1),p=>p.legs.outbound[0].riders.splice(0,1,'foreign')]){const candidate=plan();mutate(candidate);assert.throws(()=>update(populated(),{plans:[candidate]}));}});
test('registered cars must cover people needing transport',()=>{const s=populated(),p=plan();p.status='registered';p.legs.outbound[0].riders.pop();p.legs.return=structuredClone(p.legs.outbound);assert.throws(()=>update(s,{plans:[p]}));});
test('locked settlements prevent plan deletion, mutation and event edits',()=>{const s=populated();s.plans=[plan()];s.settlements=[{id:'snap',locked:true,planIds:['p'],month:'2026-09'}];assert.throws(()=>update(s,{plans:[]}),e=>e.status===409);assert.throws(()=>update(s,{plans:[{...plan(),unitYen:1}]}),e=>e.status===409);assert.throws(()=>update(s,{events:[{...s.events[0],title:'変えた'}]}),e=>e.status===409);assert.throws(()=>update(s,{settlements:[]}));assert.throws(()=>update(s,{settlements:[{...s.settlements[0],month:'2020-01'}]}));const unlocked=update(s,{settlements:[{...s.settlements[0],locked:false}]});assert.equal(update(unlocked,{plans:[]}).plans.length,0);assert.throws(()=>update(unlocked,{settlements:s.settlements}));});
test('roster and events cannot be deleted',()=>{const s=populated();assert.throws(()=>update(s,{people:[],attendance:{}}));assert.throws(()=>update(s,{events:[],attendance:{}}));});
test('LINE exchange uses PKCE and verified claims; invalid claims rejected',async()=>{
 const cfg={channel:'123',secret:'test-only'},flow={nonce:'nonce',verifier:'verifier'},valid={iss:'https://access.line.me',aud:'123',nonce:'nonce',sub:'subject',name:'名前',iat:Date.now()/1000,exp:Date.now()/1000+600};
 const transport=claims=>async(url,options)=>{assert.equal(options.redirect,'error');if(url.endsWith('/token')){assert.equal(options.body.get('code_verifier'),'verifier');return Response.json({id_token:'verified-on-server'});}assert.equal(options.body.get('id_token'),'verified-on-server');return Response.json(claims);};
 assert.equal((await exchangeLine('code',flow,cfg,'https://app.example/',transport(valid))).sub,'subject');
 for(const bad of [{iss:'evil'},{aud:'other'},{nonce:'wrong'},{exp:0},{iat:Date.now()/1000+120},{sub:''}])await assert.rejects(exchangeLine('code',flow,cfg,'https://app.example/',transport({...valid,...bad})));
});

test('gym assignment is separate, validated and protected by gym role',()=>{const s=populated();s.venues=[{id:'v',name:'体育館',courts:4}];const rel={e:{venueId:'v'}};const next=update(s,{venueAssignments:rel});assert.deepEqual(next.events,s.events);assert.deepEqual(next.training,s.training);assert.deepEqual(next.venueAssignments,rel);assert.throws(()=>update(s,{venueAssignments:rel},viewer),e=>e.status===403);s.roles['体育館']=['viewer'];assert.deepEqual(update(s,{venueAssignments:rel},viewer).venueAssignments,rel);for(const bad of [{e:{venueId:'bad'}},{bad:{venueId:'v'}},[]])assert.throws(()=>update(s,{venueAssignments:bad}));});
test('executive schedule completion updates the source once with limited authority',()=>{const s=populated();s.events.push({id:'ex',title:'幹部会',kind:'executive',date:today(),start:'18:00',end:'19:00',assignees:[],notifications:['P1M','P7D','P3D','P1D']});s.events.push({...s.events[1],id:'ex2'});const events=structuredClone(s.events);events[1].done=true;const got=update(s,{events},viewer);assert.equal(got.tasks.length,0);assert.equal(got.events.length,3);assert.equal(got.events[1].completedBy,viewer.id);assert.deepEqual(got.events[1].notifications,s.events[1].notifications);events[1].title='不正変更';assert.throws(()=>update(s,{events},viewer),e=>e.status===403);const club=structuredClone(s.events);club[0].done=true;assert.throws(()=>update(s,{events:club},viewer),e=>e.status===403);});
