import test from 'node:test';
import assert from 'node:assert/strict';
import {validateSubscription,validateNativeToken,reminderDue,reminderJobs,jobVisible,scheduleJobs,dispatchPush} from '../supabase/functions/club-api/push.mjs';
const url='https://example.com/app/',ops=new Set(['a','b']);
const s={group:{name:'部活'},events:[{id:'e',kind:'executive',title:'会議',date:'2026-10-01',assignees:[],notifications:['P1D']}],tasks:[],plans:[],notices:[],roles:{},settings:{}};
test('JST offsets and month-end clamping',()=>{assert.equal(new Date(reminderDue('2026-03-31','09:00','P1M')*1000).toISOString(),'2026-02-28T00:00:00.000Z');assert.equal(new Date(reminderDue('2026-10-01','09:00','P1D')*1000).toISOString(),'2026-09-30T00:00:00.000Z');assert.ok(Number.isNaN(reminderDue('2026-10-01','','bad')));});
test('all executives, multiple assignees, completion, old dates and same-source jobs',()=>{const now=Date.parse('2026-09-01')/1000,jobs=reminderJobs('g',s,ops,'a',url,now);assert.equal(jobs.length,2);assert.equal(new Set(jobs.map(j=>j.id)).size,2);assert.match(jobs[0].payload.url,/app\/#group-open\/g\/event\/e/);const copy=structuredClone(s);copy.events[0].assignees=['a','outside'];assert.equal(reminderJobs('g',copy,ops,'a',url,now).length,1);copy.events[0].done=true;assert.equal(reminderJobs('g',copy,ops,'a',url,now).length,0);assert.equal(reminderJobs('g',s,ops,'a',url,Date.parse('2026-10-01')/1000).length,0);});
test('dispatch rejects deleted, changed, completed and departed recipients',()=>{const j=reminderJobs('g',s,ops,'a',url,0)[0],job={...j,group_id:'g',payload:JSON.stringify(j.payload)};assert.equal(jobVisible(job,s,ops,'a',url),true);assert.equal(jobVisible(job,s,new Set(),'a',url),false);for(const change of [{done:true},{date:'2026-10-02'},{title:'変更'},{assignees:['b']},{assignmentNeedsReview:true}]){const copy=structuredClone(s);Object.assign(copy.events[0],change);assert.equal(jobVisible(job,copy,ops,'a',url),false);}});
test('subscriptions accept only push providers and valid key lengths',()=>{const sub={endpoint:'https://web.push.apple.com/Q',keys:{p256dh:Buffer.alloc(65,4).toString('base64url'),auth:Buffer.alloc(16,1).toString('base64url')}};assert.equal(validateSubscription(sub).endpoint,sub.endpoint);for(const endpoint of ['http://web.push.apple.com/Q','https://127.0.0.1/','https://web.push.apple.com.evil.test/','https://user@web.push.apple.com/','https://web.push.apple.com:8443/'])assert.throws(()=>validateSubscription({...sub,endpoint}));assert.throws(()=>validateSubscription({...sub,keys:{...sub.keys,auth:'bad'}}));});
test('native tokens remain opaque but bounded, without becoming URLs',()=>{const token='native:'+('A'.repeat(120));assert.deepEqual(validateNativeToken(token),{provider:'fcm',token});for(const bad of ['', 'short', 'A'.repeat(4097), 'A'.repeat(40)+'\n', null])assert.throws(()=>validateNativeToken(bad));});
test('unchanged notices are not resent by scheduler; explicit versions target recipients',async()=>{const calls=[],c={unsafe:async(q,p)=>{calls.push({q,p});return [];}},copy=structuredClone(s);copy.notices=[{id:'n',title:'連絡',notify:true,notifyVersion:1,assignees:['a']}];await scheduleJobs(c,'g',copy,copy,ops,'a',url,0);assert.equal(calls.filter(x=>x.q.startsWith('INSERT')).length,2);calls.length=0;await scheduleJobs(c,'g',copy,s,ops,'a',url,0);const notice=calls.filter(x=>x.q.startsWith('INSERT')).map(x=>JSON.parse(x.p[4])).filter(x=>x.resourceType==='notice');assert.equal(notice.length,1);});

test('car reminders are neither generated nor delivered from old queued jobs',()=>{const copy=structuredClone(s);copy.plans=[{id:'p',eventId:'e',notifications:['P1D']}];copy.roles={'配車':['a']};copy.settings.reminders=['P1D'];const jobs=reminderJobs('g',copy,ops,'a',url,0);assert.ok(jobs.every(j=>j.payload.resourceType!=='car'));assert.equal(jobs.length,2);assert.equal(jobVisible({id:'old',group_id:'g',recipient:'a',due:1,payload:JSON.stringify({resourceType:'car',resourceId:'p'})},copy,ops,'a',url),false);});

test('FCM dispatch retries transient errors at most three times and stops duplicate delivery',async()=>{
 const group={id:'g',owner_id:'a',data:JSON.stringify({group:{name:'部活'},events:[],tasks:[],notices:[]})},job={id:'j',group_id:'g',recipient:'a',due:Math.floor(Date.now()/1000),payload:JSON.stringify({resourceType:'test',title:'部活運営'}),status:'pending',attempts:0},subscription={id:'sub',user_id:'a',data:JSON.stringify({provider:'fcm',token:'T'.repeat(40)})},delivered=new Set();let sends=0;
 const connection={unsafe:async(q,p=[])=>{if(q==='SELECT * FROM club.groups')return [group];if(q.startsWith('SELECT user_id FROM club.memberships'))return [{user_id:'a'}];if(q.startsWith('SELECT * FROM club.jobs WHERE status=\'pending\''))return job.status==='pending'&&job.attempts<3?[{...job}]:[];if(q.startsWith('SELECT * FROM club.groups WHERE id='))return [group];if(q.startsWith('SELECT * FROM club.subscriptions'))return [subscription];if(q.startsWith('SELECT 1 FROM club.push_deliveries'))return delivered.has(p[0]+'|'+p[1])?[{exists:1}]:[];if(q.startsWith('INSERT INTO club.push_deliveries')){delivered.add(p[0]+'|'+p[1]);return [];}if(q.startsWith('UPDATE club.jobs SET status=$2,attempts')){job.status=p[1];job.attempts+=1;return [];}if(q.startsWith('UPDATE club.jobs SET status=$2 WHERE id=')){job.status=p[1];return [];}return [];}};
 const run=send=>dispatchPush(async fn=>fn(connection),send,url),fail=async()=>{sends+=1;throw Object.assign(new Error('temporary'),{statusCode:503});};
 for(let i=0;i<3;i++)await run(fail);assert.equal(sends,3);assert.equal(job.status,'failed');assert.equal(job.attempts,3);assert.equal((await run(fail)).processed,0);
 job.status='pending';job.attempts=0;const success=async()=>{sends+=1;};await run(success);assert.equal(sends,4);job.status='pending';job.attempts=0;const duplicate=await run(success);assert.equal(duplicate.processed,1);assert.equal(sends,4);assert.equal(job.status,'sent');
});
