const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function transport(){const values=new Map();let response={},request;const sandbox={window:{CLUB_HOSTING:{apiBase:'https://api.example/club-api'}},sessionStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)},fetch:async(url,options)=>{request={url,...options};return {ok:true,status:200,json:async()=>structuredClone(response)};},console};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('web/transport.js','utf8'),sandbox);return {sandbox,set:v=>response=v,request:()=>request,run:code=>vm.runInContext(code,sandbox)};}
test('auth token is stored but an invitation never replaces the session',async()=>{const t=transport();t.set({token:'session-token',csrf:'csrf'});const login=await t.run("clubRequest('/login','POST',{},'')");assert.equal(login.token,undefined);assert.equal(t.run('clubSession()'),'session-token');t.set({token:'invitation-token',expiresInDays:7});const invite=await t.run("clubRequest('/groups/g/invite','POST',{},'csrf')");assert.equal(invite.token,'invitation-token');assert.equal(t.run('clubSession()'),'session-token');assert.equal(t.request().headers.Authorization,'Bearer session-token');assert.equal(t.request().credentials,'omit');});
test('logout clears session and LINE flow',async()=>{const t=transport();t.run("clubRemember('session');sessionStorage.setItem(clubFlowKey,'flow')");t.set({ok:true});await t.run("clubRequest('/logout','POST',{},'csrf')");assert.equal(t.run('clubSession()'),'');assert.equal(t.run('sessionStorage.getItem(clubFlowKey)'),null);});
test('local Python backend retains same-origin cookie mode',async()=>{const t=transport();t.run('delete window.CLUB_HOSTING');t.set({server:true});await t.run("clubRequest('/config','GET',undefined,'')");assert.equal(t.request().url,'/api/config');assert.equal(t.request().credentials,'same-origin');});

function flowTransport(){const t=transport(),values=new Map();t.sandbox.localStorage={get length(){return values.size},key:i=>[...values.keys()][i],getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};t.sandbox.URL=URL;t.sandbox.history={replaceState:()=>{}};t.sandbox.ctx={};t.sandbox.api=async()=>({user:{id:'u'},csrf:'csrf'});return t;}
test('LINE return in another tab uses the matching short-lived flow',async()=>{const t=flowTransport();t.run("clubSaveFlow({state:'s',browserSecret:'secret',createdAt:Date.now()});sessionStorage.removeItem(clubFlowKey)");const r=await t.run("clubFinishLine(new URL('https://app.example/?state=s&code=c'))");assert.equal(r.user.id,'u');assert.equal(t.run("localStorage.getItem(clubFlowPrefix+'s')"),null);await assert.rejects(t.run("clubFinishLine(new URL('https://app.example/?state=s&code=c'))"),/見つかりません/);});
test('unrelated LINE return does not consume the current tab flow',()=>{const t=flowTransport();t.run("clubSaveFlow({state:'current',createdAt:Date.now()})");assert.equal(t.run("clubTakeFlow('other')"),null);assert.equal(t.run("JSON.parse(sessionStorage.getItem(clubFlowKey)).state"),'current');});
test('expired flow is rejected and old shared flow is pruned',async()=>{const t=flowTransport();t.run("sessionStorage.setItem(clubFlowKey,JSON.stringify({state:'old',createdAt:Date.now()-600001}));localStorage.setItem(clubFlowPrefix+'old',sessionStorage.getItem(clubFlowKey))");await assert.rejects(t.run("clubFinishLine(new URL('https://app.example/?state=old&code=c'))"),/10分/);assert.equal(t.run('localStorage.length'),0);});
test('linking cannot transfer an account session into another tab',async()=>{const t=flowTransport();t.run("clubSaveFlow({state:'s',createdAt:Date.now(),link:true});sessionStorage.removeItem(clubFlowKey)");await assert.rejects(t.run("clubFinishLine(new URL('https://app.example/?state=s&code=c'))"),/元のタブ/);});
test('login survives closing a tab; logout removes persistent credentials',async()=>{const t=flowTransport();t.run("clubRemember('session');sessionStorage.removeItem(clubSessionKey)");assert.equal(t.run('clubSession()'),'session');assert.equal(t.run('localStorage.getItem(clubSessionKey)'),'session');t.set({ok:true});await t.run("clubRequest('/logout','POST',{},'csrf')");assert.equal(t.run('clubSession()'),'');assert.equal(t.run('localStorage.getItem(clubSessionKey)'),null);});
test('existing tab session migrates without requiring another login',()=>{const t=flowTransport();t.run("sessionStorage.setItem(clubSessionKey,'existing')");assert.equal(t.run('clubSession()'),'existing');assert.equal(t.run('localStorage.getItem(clubSessionKey)'),'existing');assert.equal(t.run('sessionStorage.getItem(clubSessionKey)'),null);});
test('expired server session clears persistent login',async()=>{const t=flowTransport();t.run("clubRemember('expired')");t.sandbox.fetch=async()=>({ok:false,status:401,json:async()=>({detail:'expired'})});await assert.rejects(t.run("clubRequest('/session','GET')"),/expired/);assert.equal(t.run('clubSession()'),'');});
test('Safari callback can be redeemed only with the pending flow in the original PWA',async()=>{const safari=flowTransport(),pwa=flowTransport();let payload;pwa.run("clubSaveFlow({state:'pwa-state',browserSecret:'pwa-secret',createdAt:Date.now()});sessionStorage.removeItem(clubFlowKey)");await assert.rejects(safari.run("clubFinishLine(new URL('https://app.example/?state=pwa-state&code=line-code'))"),e=>{payload=e.handoffCode;return !!payload;});assert.equal(payload.includes('pwa-secret'),false);pwa.sandbox.location={href:'https://app.example/#welcome'};let request;pwa.sandbox.api=async(path,method,data)=>{request={path,data};return {user:{id:'pwa-user'},csrf:'csrf'};};pwa.sandbox.returnCode=payload;const result=await pwa.run('clubImportLine(returnCode)');assert.equal(result.user.id,'pwa-user');assert.equal(request.data.browserSecret,'pwa-secret');assert.equal(request.data.code,'line-code');assert.equal(pwa.run('clubPendingLine()'),null);await assert.rejects(pwa.run('clubImportLine(returnCode)'),/10分/);});
test('a foreign or malformed return code cannot consume a pending PWA login',async()=>{const t=flowTransport();t.run("clubSaveFlow({state:'ours',createdAt:Date.now()})");t.sandbox.returnCode='CLUB-LINE:'+JSON.stringify({state:'foreign',code:'c'});await assert.rejects(t.run('clubImportLine(returnCode)'),/10分/);assert.equal(t.run('clubPendingLine().state'),'ours');t.sandbox.returnCode='CLUB-LINE:{';await assert.rejects(t.run('clubImportLine(returnCode)'),/確認コード/);});
test('unauthenticated PWA bootstrap retains its pending LINE flow',async()=>{const t=flowTransport();t.run("clubSaveFlow({state:'pending',createdAt:Date.now()})");t.sandbox.fetch=async()=>({ok:false,status:401,json:async()=>({detail:'login'})});await assert.rejects(t.run("clubRequest('/session','GET')"));assert.equal(t.run('clubPendingLine().state'),'pending');t.run('clubForget()');assert.equal(t.run('clubPendingLine()'),null);});
