"""v0.9 UI acceptance tests. Managed Chromium, injected unchanged scripts with storage adapter.
Covers changed user workflows; no real LINE login or OS save success is simulated.
"""
from pathlib import Path
import sys,json,base64
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'qa';sys.path.insert(0,str(ROOT))
helpers={'__file__':str(ROOT/'tests/browser_checks.py')};s=(ROOT/'tests/browser_checks.py').read_text();exec(s[:s.index('with sync_playwright()')],helpers)
results=[]
def check(name,ok):
 results.append({'name':name,'pass':bool(ok)});print(('PASS ' if ok else 'FAIL ')+name,flush=True)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium',args=['--no-sandbox']);page=b.new_page(viewport={'width':390,'height':844});page.set_default_timeout(5000);errors=[]
 page.on('pageerror',lambda e:errors.append(str(e)));page.on('dialog',lambda d:d.accept())
 page.set_content(helpers['html']().replace("location.hash='home';","location.hash='';"));page.wait_for_function('ctx.ready');page.wait_for_timeout(100)
 def route(r):page.evaluate('(r)=>location.hash=r',r);page.wait_for_timeout(65)
 def idle():page.wait_for_function('!wf.pending&&!ctx.busy');page.wait_for_timeout(60)
 def shot(name):page.evaluate("document.getElementById('toast-root').innerHTML=''");page.screenshot(path=str(OUT/(name+'.png')))
 check('startup separates login from workspace',page.locator('[data-act="wf-demo"]').count()==1 and page.locator('nav').count()==0)
 check('LINE button disabled until configuration',page.locator('button.wf-line').is_disabled() and '接続設定前' in page.locator('#app').inner_text())
 shot('v09_login');page.locator('[data-act="wf-demo"]').click();idle()
 check('demo opens real group selection, not fake LINE login',page.locator('h1').inner_text()=='グループを選ぶ' and page.locator('nav').count()==0 and page.evaluate('ctx.user===null'))
 shot('v09_groups');original=page.evaluate('state.group.id');page.locator('[data-act="wf-open-group"]').first.click();idle()
 check('selecting a group opens existing five-tab home',page.locator('nav a').count()==5 and page.locator('main .section').count()==2)
 route('account');check('account works outside group tab layout',page.locator('nav').count()==0 and page.locator('[data-form="wf-account"]').count()==1)
 page.locator('[name="name"]').fill('確認用表示名');page.locator('[data-form="wf-account"] button').click();idle()
 check('display name saved without changing user id',page.evaluate('oName(state.currentUser)')=='確認用表示名' and page.evaluate('state.currentUser')=='u1')
 shot('v09_account');route('group-create');page.locator('[name="name"]').fill('別グループの検証');page.locator('[data-form="wf-create-group"] button').click();idle()
 second=page.evaluate('state.group.id');check('new demo group has separate empty data',second!=original and page.evaluate('state.events.length===0&&state.people.length===0'))
 route('attendance');check('empty-group attendance handled', '部活予定がありません' in page.locator('#app').inner_text())
 route('groups');check('multiple groups available',page.locator('[data-act="wf-open-group"]').count()==2)
 page.locator(f'[data-act="wf-open-group"][data-id="{original}"]').click();idle();check('original group preserved after switching',page.evaluate('state.events.length>0&&state.people.length>0'))
 route('operators');check('roster and operators clearly separated', '部員名簿とは別' in page.locator('#app').inner_text());shot('v09_operators')
 route('operator/u2');page.locator('[name="role"][value="練習メニュー"]').check();page.locator('[data-form="wf-operator-roles"] button').click();idle();check('operator permission picker saves selected scope',page.evaluate('state.roles["練習メニュー"].includes("u2")'))
 route('invite');check('demo cannot mint a fake real invitation',page.locator('[data-act="wf-make-invite"]').is_disabled());shot('v09_invite')
 page.locator('[data-act="wf-invite-preview"]').click();idle();check('invitation preview shows group and initial permission',page.locator('[data-act="wf-join-confirm"]').count()==1 and '閲覧のみ' in page.locator('#app').inner_text());shot('v09_join')
 page.locator('[data-act="wf-join-confirm"]').click();idle();check('demo invitation does not fabricate a LINE identity',page.evaluate('ctx.user===null'))
 page.evaluate('ClubApp.reset()');route('car/plan1')
 check('carpool mode toggle always visible',page.locator('[data-act="wf-car-mode"]').count()==2)
 shot('v09_carpool_same');before=page.evaluate('JSON.stringify(plan("plan1").legs.outbound)')
 page.locator('[data-act="wf-car-mode"][data-value="separate"]').click();idle();check('split preserves both placements',page.evaluate('!plan("plan1").linked') and page.evaluate('JSON.stringify(plan("plan1").legs.outbound)')==before and page.evaluate('JSON.stringify(plan("plan1").legs.return)')==before)
 check('split exposes explicit outbound and return tabs',page.locator('[data-act="car-leg"]').count()==2)
 page.locator('[data-act="car-leg"][data-value="return"]').click();page.wait_for_timeout(60)
 page.evaluate('moveMember("plan1","m9",{kind:"passenger",carId:"c2"},"return");render()')
 check('return edit does not change outbound',page.evaluate('JSON.stringify(plan("plan1").legs.outbound)')==before and page.evaluate('plan("plan1").legs.return.find(c=>c.id==="c2").riders.includes("m9")'))
 shot('v09_carpool_separate');ret=page.evaluate('JSON.stringify(plan("plan1").legs.return)')
 page.locator('[data-act="wf-car-mode"][data-value="same"]').click();idle();check('merge asks which leg and never silently overwrites',page.locator('[data-act="wf-car-merge"]').count()==2 and page.evaluate('!plan("plan1").linked'))
 shot('v09_carpool_merge');page.locator('[data-act="wf-car-merge"][data-leg="return"]').click();idle();check('explicit return selection merged both legs',page.evaluate('plan("plan1").linked') and page.evaluate('JSON.stringify(plan("plan1").legs.outbound)')==ret and page.evaluate('JSON.stringify(plan("plan1").legs.return)')==ret)
 page.locator('[data-act="undo"]').click();page.wait_for_timeout(60);check('merge undo restores split state',page.evaluate('!plan("plan1").linked') and page.evaluate('JSON.stringify(plan("plan1").legs.outbound)')==before)
 page.evaluate('ClubApp.reset()');route('car/plan1');page.evaluate('state.attendance["e1|m4"]=false;plan("plan1").unitYen=450;plan("plan1").legDates={outbound:"2026-10-01",return:"2026-10-02"};plan("plan1").notifications=["P1D"];plan("plan1").adjustments={"outbound|m5":{unitYen:100}};render()')
 before=page.evaluate('JSON.stringify(plan("plan1"))');src=page.evaluate('JSON.stringify(plan("plan0"))')
 page.locator('[data-act="wf-car-copy-open"]').click();idle();check('copy chooses source before mutating target',page.locator('[href^="#car-copy-confirm/"]').count()>0 and page.evaluate('JSON.stringify(plan("plan1"))')==before)
 page.locator('[href="#car-copy-confirm/plan1/plan0"]').click();page.wait_for_timeout(70)
 check('copy confirmation names source destination and exclusion', '細川' in page.locator('.wf-summary-row').first.inner_text() and 'コピー元' in page.locator('#app').inner_text())
 shot('v09_carpool_copy');page.locator('[data-act="wf-car-copy-apply"]').click();idle()
 check('copy excludes absentees and keeps source immutable',page.evaluate('!plan("plan1").legs.outbound.flatMap(c=>[c.driver,...c.riders]).includes("m4")') and page.evaluate('JSON.stringify(plan("plan0"))')==src)
 check('copy preserves target price dates and reminders, clears personal adjustments',page.evaluate('plan("plan1").unitYen===450&&plan("plan1").legDates.return==="2026-10-02"&&JSON.stringify(plan("plan1").notifications)===JSON.stringify(["P1D"])&&Object.keys(plan("plan1").adjustments).length===0'))
 page.locator('[data-act="undo"]').click();page.wait_for_timeout(60);check('copy undo restores original target',page.evaluate('JSON.stringify(plan("plan1"))')==before)
 # Finish a valid table without changing the presentation contract.
 page.evaluate('ClubApp.reset();moveMember("plan1","m9",{kind:"passenger",carId:"c2"});moveMember("plan1","m11",{kind:"passenger",carId:"c3"});moveMember("plan1","m12",{kind:"passenger",carId:"c3"});render()')
 route('car-table/plan1');check('table image action is discoverable and driver headings preserved',page.locator('[data-act="wf-car-image"]').is_enabled() and page.locator('.ride-table th').all_text_contents()==['池田','中島','山口'])
 page.locator('[data-act="wf-car-image"]').click();idle();check('car image shows preview with distinct save and share',page.locator('.image-preview').count()==1 and page.locator('[data-act="wf-image-save"]').count()==1 and page.locator('[data-act="wf-image-share"]').count()==1)
 shot('v09_carpool_image');(OUT/'v09_carpool_export.png').write_bytes(base64.b64decode(page.evaluate('wf.image.cv.toDataURL().split(",")[1]')))
 check('image preview has PNG payload',page.evaluate('wf.image.blob.type==="image/png"&&wf.image.blob.size>1000'))
 page.locator('[data-act="close-modal"]').click();route('calendar');check('calendar retains executive overlay',page.locator('[data-act="calendar-filter"]').count()==2)
 page.locator('[data-act="calendar-filter"][data-value="all"]').click();page.wait_for_timeout(60)
 check('executive overlay still projects task deadlines',page.locator('.event-chip.task').count()>0)
 page.locator('[data-act="wf-calendar-image"]').click();idle();check('calendar export defaults to club-only despite overlay',page.locator('[name="wf-calendar-scope"][value="club"]').is_checked())
 shot('v09_calendar_options');page.locator('[data-act="wf-calendar-preview"]').click();idle();check('calendar export has deliberate audience in filename',page.evaluate('wf.image.name.includes("部活のみ")'))
 shot('v09_calendar_image');(OUT/'v09_calendar_export.png').write_bytes(base64.b64decode(page.evaluate('wf.image.cv.toDataURL().split(",")[1]')))
 page.locator('[data-act="close-modal"]').click()
 # locked plans never allow the new mutation path.
 route('car/plan1');page.evaluate('state.settlements.push({id:"lock-test",locked:true,planIds:["plan1"]});render()')
 check('new car controls honor monthly lock',page.locator('[data-act="wf-car-mode"]').first.is_disabled() and page.locator('[data-act="wf-car-copy-open"]').is_disabled())
 page.evaluate('ClubApp.reset()')
 for width in [320,390,768]:
  page.set_viewport_size({'width':width,'height':844})
  for r in ['welcome','groups','account','operators','invite','car/plan1','car-copy-confirm/plan1/plan0','calendar']:
   route(r);check(f'new workflows no horizontal overflow {width} {r}',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
 check('no uncaught workflow errors',not errors)
 b.close()
(OUT/'workflow-browser-results.json').write_text(json.dumps({'results':results,'errors':errors,'limitations':['Storage adapter / direct script injection','No real LINE account or OS share tested']},ensure_ascii=False,indent=2))
print(f'{sum(r["pass"] for r in results)}/{len(results)} pass')
if any(not r['pass'] for r in results):raise SystemExit(1)
