-- Run once as the database administrator. No application tables are exposed
-- through Supabase's public Data API. The app uses a dedicated database role.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='club_runtime') THEN
    CREATE ROLE club_runtime NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE;
  END IF;
END $$;
CREATE SCHEMA IF NOT EXISTS club;
REVOKE ALL ON SCHEMA club FROM PUBLIC;
GRANT USAGE ON SCHEMA club TO club_runtime;

CREATE TABLE IF NOT EXISTS club.schema_version(id INTEGER PRIMARY KEY, version INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS club.users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS club.sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL,csrf TEXT NOT NULL,expires DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS club.groups(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,data TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS club.memberships(group_id TEXT NOT NULL,user_id TEXT NOT NULL,PRIMARY KEY(group_id,user_id));
CREATE TABLE IF NOT EXISTS club.invites(token TEXT PRIMARY KEY,group_id TEXT NOT NULL,expires DOUBLE PRECISION NOT NULL,used INTEGER NOT NULL DEFAULT 0,created_at DOUBLE PRECISION NOT NULL DEFAULT 0,created_by TEXT);
CREATE TABLE IF NOT EXISTS club.audit(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,group_id TEXT,user_id TEXT,action TEXT,created_at TEXT,details TEXT);
CREATE TABLE IF NOT EXISTS club.subscriptions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS club.jobs(id TEXT PRIMARY KEY,group_id TEXT NOT NULL,recipient TEXT NOT NULL,due DOUBLE PRECISION NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0);
ALTER TABLE club.jobs ADD COLUMN IF NOT EXISTS claimed_at DOUBLE PRECISION NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS club.push_deliveries(job_id TEXT NOT NULL,subscription_id TEXT NOT NULL,PRIMARY KEY(job_id,subscription_id));
CREATE TABLE IF NOT EXISTS club.push_config(id INTEGER PRIMARY KEY CHECK(id=1),public_key TEXT NOT NULL,private_key TEXT NOT NULL,worker_token TEXT NOT NULL,enabled BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS club.identities(provider TEXT NOT NULL,channel TEXT NOT NULL,subject TEXT NOT NULL,user_id TEXT NOT NULL,created_at DOUBLE PRECISION NOT NULL,PRIMARY KEY(provider,channel,subject),UNIQUE(provider,channel,user_id));
CREATE TABLE IF NOT EXISTS club.login_flows(state_hash TEXT PRIMARY KEY,cookie_hash TEXT NOT NULL,nonce TEXT NOT NULL,verifier TEXT NOT NULL,link_user_id TEXT,expires DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS club.login_limits(client_hash TEXT PRIMARY KEY,window_start DOUBLE PRECISION NOT NULL,attempts INTEGER NOT NULL);

CREATE INDEX IF NOT EXISTS memberships_user_idx ON club.memberships(user_id);
CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON club.sessions(expires);
ALTER TABLE club.invites ADD COLUMN IF NOT EXISTS max_uses INTEGER NOT NULL DEFAULT 1 CHECK(max_uses BETWEEN 1 AND 100);
ALTER TABLE club.invites ADD COLUMN IF NOT EXISTS use_count INTEGER NOT NULL DEFAULT 0 CHECK(use_count>=0);
UPDATE club.invites SET use_count=1 WHERE used=1 AND use_count=0;
CREATE INDEX IF NOT EXISTS invites_group_idx ON club.invites(group_id);
CREATE INDEX IF NOT EXISTS subscriptions_user_idx ON club.subscriptions(user_id);
CREATE INDEX IF NOT EXISTS jobs_due_idx ON club.jobs(due) WHERE status='pending';
CREATE INDEX IF NOT EXISTS jobs_group_idx ON club.jobs(group_id);
CREATE INDEX IF NOT EXISTS flows_expiry_idx ON club.login_flows(expires);

DO $$ DECLARE item RECORD; BEGIN
  FOR item IN SELECT tablename FROM pg_tables WHERE schemaname='club' LOOP
    EXECUTE format('ALTER TABLE club.%I ENABLE ROW LEVEL SECURITY',item.tablename);
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='club' AND tablename=item.tablename AND policyname='server_only') THEN
      EXECUTE format('CREATE POLICY server_only ON club.%I TO club_runtime USING (true) WITH CHECK (true)',item.tablename);
    END IF;
  END LOOP;
END $$;
REVOKE ALL ON ALL TABLES IN SCHEMA club FROM PUBLIC;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA club TO club_runtime;
REVOKE INSERT,UPDATE,DELETE ON club.schema_version FROM club_runtime;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA club TO club_runtime;
INSERT INTO club.schema_version VALUES(1,1) ON CONFLICT(id) DO NOTHING;

REVOKE INSERT,UPDATE,DELETE ON club.push_config FROM club_runtime;
