/* Actual integrated application. The HTML handoff's visual components are reused;
   original menu time semantics are preserved in domain.js, rather than an iframe. */
'use strict';
const D=ClubDomain;
const MODULE_KEYS=['group','people','events','tasks','notices','plans','venues','venueAssignments','equipment','attendance','training','settlements','settings','roles'];
const MODULE_ROLES={events:'予定',tasks:'やること',notices:'お知らせ',plans:'配車',settlements:'配車',attendance:'出欠',people:'部員',venues:'体育館',venueAssignments:'体育館',training:'練習メニュー',equipment:'備品'};
const LEGACY_DEFAULT={categories:[{id:'cat_basic',name:'基礎'},{id:'cat_knock',name:'ノック'},{id:'cat_footwork',name:'フットワーク'},{id:'cat_game',name:'ゲーム'},{id:'cat_core',name:'体幹'},{id:'cat_other',name:'その他'}],menus:[{id:'menu_1',name:'基礎打ち',categoryId:'cat_basic',seconds:300,requiresSets:true},{id:'menu_2',name:'スマッシュノック',categoryId:'cat_knock',seconds:120,requiresSets:true},{id:'menu_3',name:'フットワーク',categoryId:'cat_footwork',seconds:180,requiresSets:true},{id:'menu_4',name:'ゲーム練習',categoryId:'cat_game',seconds:480,requiresSets:true},{id:'menu_5',name:'体幹トレーニング',categoryId:'cat_core',seconds:600,requiresSets:false},{id:'menu_6',name:'休憩',categoryId:'cat_other',seconds:300,requiresSets:false}]};
const ctx={mode:'loading',ready:false,user:null,csrf:'',groups:[],base:null,busy:false,conflict:null,pushConfig:{},authTab:'login'};
let practiceDraft=null,practiceCategory='all',practiceEvent='',previewCanvas=null,previewPracticeSource=null,practiceReorder=false,practiceCategoryEdit=false,practiceHistoryEdit=false,previewPracticeHistorySaved=false,menuDrag=null,categoryDrag=null;
ui.settlementMonth=DEMO_TODAY.slice(0,7);ui.calendarYear=Number(DEMO_TODAY.slice(0,4));ui.calendarMonth=Number(DEMO_TODAY.slice(5,7))-1;
const origSeed=seed,origRender=render,origModal=modal,origClose=closeModal;
function demoSeed(){const s=origSeed();const shift=Math.round((new Date(DEMO_TODAY+'T12:00:00Z')-new Date('2026-09-05T12:00:00Z'))/86400000);for(const arr of [s.events,s.tasks,s.notices])arr.forEach(x=>x.date=D.addDays(x.date,shift));s.schema=2;s.ownerId='u1';s.roles['部員']=['u1'];s.training={...clone(LEGACY_DEFAULT),sheets:[],history:[]};s.settlements=[];s.plans.forEach(p=>{p.notifications=['P7D','P1D'];p.legDates={outbound:eventDate(s,p.eventId),return:eventDate(s,p.eventId)}});return s;}
function eventDate(s,id){return s.events.find(e=>e.id===id).date;}
function normalize(s){s.venueAssignments||={};s.schema=2;s.training||={categories:[],menus:[],sheets:[],history:[]};s.training.categories||=[];s.training.menus||=[];s.training.sheets||=[];s.training.history||=[];s.training.menus.forEach((m,i)=>{if(m.order===undefined)m.order=i;});s.settlements||=[];s.roles['部員']||=[];s.plans.forEach(p=>{p.adjustments||={};p.legDates||={outbound:eventDate(s,p.eventId),return:eventDate(s,p.eventId)}});D.seedAttendance(s);return s;}
function own(){return ctx.mode==='demo'||state.currentUser===state.ownerId;}
function edit(key){return own()||state.roles[MODULE_ROLES[key]||key]?.includes(state.currentUser);}
function operationalTasks(){return [...state.tasks,...state.events.filter(e=>e.kind==='executive'&&!e.cancelled).map(e=>({...e,id:'exec:'+e.id,time:e.start||'',executiveId:e.id}))];}
function ownTask(t){return !t.assignmentNeedsReview&&(!t.assignees.length||t.assignees.includes(state.currentUser));}
function noticeVisible(n){if(own())return true;if(n.assignmentNeedsReview)return false;if(n.targetMode==='role')return n.targetRoles?.some(r=>state.roles[r]?.includes(state.currentUser));return !n.assignees.length||n.assignees.includes(state.currentUser);}
async function api(path,method='GET',data){return clubRequest(path,method,data,ctx.csrf);}
function safeLocal(key,value){try{localStorage.setItem(key,value);return true}catch{return false}}
persist=function(){
 if(ctx.mode==='demo'){if(!safeLocal(STORAGE_KEY,JSON.stringify(state))){toast('保存できません。バックアップしてください');return false;}return true;}
 if(ctx.mode!=='server'||!ctx.user||!ctx.base){toast('ログインしてください');return false;}
 if(ctx.busy){toast('保存中です');return false;}
 const changes={};for(const k of MODULE_KEYS)if(JSON.stringify(state[k])!==JSON.stringify(ctx.base[k]))changes[k]=clone(state[k]);
 if(!Object.keys(changes).length)return true;
 if(changes.attendance&&!edit('attendance')&&(changes.events||changes.people))delete changes.attendance;
 const attempted=clone(state),gid=state.group.id;ctx.busy=true;document.body.classList.add('saving');
 ctx.savePromise=api('/groups/'+gid+'/state','PATCH',{version:ctx.base.version,changes}).then(s=>{state=normalize(s);ctx.base=clone(state);ctx.conflict=null;}).catch(err=>{safeLocal('club-unsaved-'+gid,JSON.stringify(attempted));ctx.conflict={message:err.message,state:attempted};state=clone(ctx.base);toast(err.message);}).finally(()=>{ctx.busy=false;document.body.classList.remove('saving');render();});
 return true;
};
const oldTaskRow=taskRow;
taskRow=function(t,show=false){let html=oldTaskRow(t,show);if(!edit('tasks')&&!ownTask(t))html=html.replace('data-act="task-toggle"','disabled data-act="task-toggle"');return html;};
renderHome=function(){const mine=operationalTasks().filter(t=>!t.done&&!t.deleted&&ownTask(t)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));return shell(state.group.name,'home',`<section class="section"><div class="section-head"><h2>お知らせ</h2><a class="small muted" href="#notices">すべて ›</a></div>${state.notices.filter(noticeVisible).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(n=>`<a class="row" href="#notice/${n.id}"><span class="notice-date">${n.date.slice(5).replace('-','/')}</span><span class="row-main">${esc(n.title)}</span></a>`).join('')||'<p class="empty">ありません</p>'}</section><section class="section"><div class="section-head"><h2>自分のやること</h2><a class="small muted" href="#tasks">すべて ›</a></div>${mine.map(t=>taskRow(t)).join('')||'<p class="empty">ありません</p>'}</section>`,'',action('group-picker',icon('chev'),'aria-label="グループを切り替える"','icon-btn'));};
renderTasks=function(){const ts=operationalTasks().filter(t=>!t.deleted&&(ui.taskTab==='done'?t.done:!t.done&&(ui.taskTab==='all'||ownTask(t)))).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));return shell('やること','tasks',segments([['self','自分'],['all','全体'],['done','完了']],ui.taskTab,'task-tab')+ts.map(t=>taskRow(t,ui.taskTab!=='self')).join('')+(ts.length?'':'<p class="empty">ありません</p>'),'',edit('tasks')?`<a class="icon-btn" href="#task-edit" aria-label="やることを追加">${icon('plus')}</a>`:'');};
renderTaskEdit=function(id,related=''){const t=state.tasks.find(x=>x.id===id)||{title:'',date:DEMO_TODAY,time:'23:59',assignees:[],memo:'',notifications:state.settings.reminders};return formShell(id?'やることを編集':'やることを追加','tasks','task',field('やること','title',t.title,'text','required maxlength="200"')+assigneeField(t.assignees)+`<div class="inline-fields">${field('期限日','date',t.date,'date','required')}${field('期限時刻','time',t.time,'time','required')}</div>`+memoField(t.memo)+notifications(t.notifications)+`<input type="hidden" name="related" value="${esc(t.relatedEventId||related)}">`+(id?action('delete-task','削除',`data-id="${id}"`,'text-btn danger-button'):''),id?'task/'+id:'tasks',id);};
renderCalendar=function(){const y=ui.calendarYear,m=ui.calendarMonth,first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());let cells='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const ds=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,items=D.calendarItems(state,ds,ui.showExec);cells+=`<button class="day ${d.getMonth()!==m?'other':''} ${ds===DEMO_TODAY?'today':''}" data-act="open-day" data-date="${ds}" aria-label="${ds} ${items.length}件"><span class="day-num">${d.getDate()}</span>${items.slice(0,2).map(e=>`<span class="event-chip ${e.kind==='executive'?'exec':e.kind==='task'?'task':''}">${esc(e.title)}</span>`).join('')}${items.length>2?`<span class="small muted">＋${items.length-2}</span>`:''}</button>`;}
 return shell('予定','calendar',`<div class="month-head">${action('month','‹','data-dir="-1" aria-label="前月"','icon-btn')}<h2>${y}年${m+1}月</h2>${action('month','›','data-dir="1" aria-label="翌月"','icon-btn')}</div>${segments([['club','部活のみ'],['all','幹部予定も表示']],ui.showExec?'all':'club','calendar-filter')}<div class="calendar">${'日月火水木金土'.split('').map(x=>`<div class="weekday">${x}</div>`).join('')}${cells}</div><div class="calendar-footer">${action('calendar-image','画像')}</div>`,'',edit('events')?`<a class="icon-btn" href="#event-edit" aria-label="予定を追加">${icon('plus')}</a>`:'');};
renderDay=function(day){const items=D.calendarItems(state,day,ui.showExec);return shell(jpDate(day,true),'calendar',items.map(x=>`<a class="day-item" href="#${x.type}/${x.id}"><span class="time-label">${x.time||'時刻なし'}</span><div><div class="row-title">${esc(x.title)}</div><div class="row-sub">${esc(x.kind==='club'?venue(x.venueId)?.name||'体育館未設定':aNames(x.assignees))}</div></div></a>`).join('')||'<p class="empty">予定はありません</p>','calendar',edit('events')?`<a class="icon-btn" href="#event-edit//${day}" aria-label="予定を追加">${icon('plus')}</a>`:'');};
renderEventEdit=function(id,day){const e=event(id)||{title:'練習',date:day||DEMO_TODAY,endDate:'',start:'',end:'',kind:'club',venueId:'',assignees:[],memo:'',courts:null};return formShell(id?'予定を編集':'予定を追加','calendar','event2',`<label class="field"><span class="label">予定</span><select name="kind"><option value="club" ${e.kind==='club'?'selected':''}>部活予定</option><option value="executive" ${e.kind==='executive'?'selected':''}>幹部予定</option></select></label>`+field('タイトル','title',e.title,'text','required maxlength="200"')+field('日付','date',e.date,'date','required')+`<div class="inline-fields">${field('開始','start',e.start,'time')}${field('終了','end',e.end,'time')}</div><details class="advanced"><summary>複数日・繰り返し</summary><div class="field-gap"></div>${field('終了日','endDate',e.endDate||'','date')}${id?'':`<label class="field"><span class="label">登録方法</span><select name="repeatMode"><option value="single">この日だけ</option><option value="weekly">曜日で繰り返す</option><option value="multiple">日付を選ぶ</option></select></label><div data-repeat="weekly" hidden>${field('繰り返す期限','repeatUntil',D.addMonths(e.date,1),'date')}<div class="week-checks">${'日月火水木金土'.split('').map((x,i)=>`<label><input type="checkbox" name="weekday" value="${i}"><span>${x}</span></label>`).join('')}</div></div><div data-repeat="multiple" hidden><input type="date" id="batch-date"><div class="form-actions">${action('batch-date-add','日付を追加','','secondary')}</div><div id="batch-dates" class="chips" style="margin-top:12px"></div></div>`}</details><div data-club-fields ${e.kind!=='club'?'hidden':''}><label class="field"><span class="label">体育館</span><select name="venue"><option value="">未設定</option>${state.venues.map(v=>`<option value="${v.id}" ${e.venueId===v.id?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><details class="advanced"><summary>使用コート数</summary>${field('面数','courts',e.courts??'','number','min="1" max="30"')}</details></div><div data-exec-fields ${e.kind!=='executive'?'hidden':''}>${assigneeField(e.assignees)}</div>`+memoField(e.memo)+notifications(e.notifications||state.settings.reminders)+(id?action('cancel-event',e.cancelled?'中止を取り消す':'予定を中止',`data-id="${id}"`,'text-btn danger-button'):''),id?'event/'+id:'calendar',id);};
const originalEvent=renderEvent;
renderEvent=function(id){let html=originalEvent(id),e=event(id);if(!e)return html;if(e.cancelled)html=html.replace('<main class="content">','<main class="content"><div class="warning">中止</div>');if(e.endDate&&e.endDate!==e.date)html=html.replace(jpDate(e.date,true),jpDate(e.date,true)+'〜'+jpDate(e.endDate));if(!edit('events'))html=html.replace(/<a class="text-btn" href="#event-edit[^<]*<\/a>/g,'');return html;};
clubEvents=function(){return state.events.filter(e=>e.kind==='club'&&!e.cancelled).sort((a,b)=>(a.date+(a.start||'')).localeCompare(b.date+(b.start||'')));};
const originalAttendance=renderAttendance;
renderAttendance=function(){if(!clubEvents().length)return shell('出欠','operations','<p class="empty">部活予定はありません</p>','operations');if(!state.people.some(p=>p.active))return shell('出欠','operations','<p class="empty">部員を登録してください</p>','operations');if(!event(ui.attendanceEvent)||event(ui.attendanceEvent).cancelled)ui.attendanceEvent=clubEvents().find(e=>e.date>=DEMO_TODAY)?.id||clubEvents()[0].id;if(!person(ui.attendanceMember))ui.attendanceMember=state.people[0].id;let html=originalAttendance();if(!edit('attendance'))html=html.replaceAll('data-act="attendance-toggle"','disabled data-act="attendance-toggle"');return html;};
renderNotices=function(){return shell('お知らせ','home',state.notices.filter(noticeVisible).sort((a,b)=>b.date.localeCompare(a.date)).map(n=>`<a class="row" href="#notice/${n.id}"><div class="row-main"><div class="row-title">${esc(n.title)}</div><div class="row-sub">${jpDate(n.date)}</div></div>${icon('chev','chev')}</a>`).join('')||'<p class="empty">ありません</p>','home',edit('notices')?`<a class="icon-btn" href="#notice-edit" aria-label="投稿を追加">${icon('plus')}</a>`:'');};
renderNoticeEdit=function(id){const n=state.notices.find(n=>n.id===id)||{title:'',body:'',assignees:[],notify:true,targetMode:'all'};return formShell(id?'お知らせを編集':'お知らせを追加','home','notice2',field('タイトル','title',n.title,'text','required maxlength="200"')+`<label class="field"><span class="label">本文</span><textarea name="body" required>${esc(n.body)}</textarea></label><div class="field"><span class="label">対象</span><select name="targetMode"><option value="all" ${n.targetMode==='all'?'selected':''}>全員</option><option value="people" ${n.targetMode==='people'?'selected':''}>メンバーを選ぶ</option><option value="role" ${n.targetMode==='role'?'selected':''}>担当を選ぶ</option></select></div><div data-target="people" ${n.targetMode!=='people'?'hidden':''}>${assigneeField(n.assignees)}</div><div data-target="role" ${n.targetMode!=='role'?'hidden':''}><div class="options">${Object.keys(state.roles).map(r=>`<label class="option"><input type="checkbox" name="targetRole" value="${esc(r)}" ${n.targetRoles?.includes(r)?'checked':''}>${esc(r)}</label>`).join('')}</div></div><label class="option" style="margin-top:16px"><input type="checkbox" name="push" ${!id?'checked':''}>${id?'通知して更新':'通知する'}</label>`+(id?action('delete-notice','削除',`data-id="${id}"`,'text-btn danger-button'):''),'notices',id);};
/* Practice menu: legacy 4/5-person calculation + native group-scoped saved sheets. */
function sessionInfo(eid){const e=event(eid);if(!e)return null;const minutes=e.start&&e.end?Math.round((new Date((e.endDate||e.date)+'T'+e.end)-new Date(e.date+'T'+e.start))/60000):null;return {date:e.date,venue:eventVenue(e)?.name||'',participants:participants(e.id).length,courts:state.venueAssignments?.[e.id]?eventVenue(e)?.courts||null:e.courts||eventVenue(e)?.courts||null,minutes,start:e.start||'',end:e.end||''};}
function sessionSummary(info){return info?`${jpDate(info.date)}　${esc(info.venue||'体育館未設定')}<div class="row-sub">${info.participants}人${info.courts?'　'+info.courts+'面':''}${info.minutes!==null?'　'+info.minutes+'分':''}</div>`:'予定を選択';}
function practicePicker(label='練習日',id=practiceEvent){return `<div class="field"><span class="label">${label}</span>${action('practice-event-pick',`<span>${sessionSummary(sessionInfo(id))}</span>${icon('chev','chev')}`,'','selector')}</div>`;}
renderPractice=function(){const e=event(practiceEvent);return shell('練習メニュー','operations',(e?`<div class="session-compact">${sessionSummary(sessionInfo(e.id))}</div>`:'')+entry('メニュー表作成','practice-new','paper')+entry('メニュー一覧','menu-list','paper')+entry('分類一覧','practice-categories','grid')+entry('練習メニュー履歴','practice-saved','clock')+(state.training.menus.length?'':`<div class="form-actions">${edit('training')?action('practice-defaults','初期メニューを追加','','secondary full'):''}</div>`),'operations');};
function newPractice(id){if(id){const sh=state.training.sheets.find(x=>x.id===id);if(!sh)return;practiceDraft=clone(sh);}else practiceDraft={id:UID(),title:'練習メニュー',eventId:practiceEvent||'',context:sessionInfo(practiceEvent),patterns:[4,5],rows:[],memo:'',updatedAt:null};practiceCategory='all';practiceReorder=false;go('practice-select');}
function categoryIndex(id){const i=state.training.categories.findIndex(c=>c.id===id);return i<0?999:i;}
function sortedTrainingMenus(list=state.training.menus){return [...list].sort((a,b)=>categoryIndex(a.categoryId)-categoryIndex(b.categoryId)||(a.order??0)-(b.order??0)||String(a.name).localeCompare(String(b.name),'ja'));}
function normalizeMenuOrders(categoryId){sortedTrainingMenus(state.training.menus.filter(m=>m.categoryId===categoryId)).forEach((m,i)=>m.order=i);}
function categoriesTabs(){return `<div class="category-tabs">${[{id:'all',name:'すべて'},...state.training.categories].map(c=>action('practice-category',esc(c.name),`data-id="${c.id}"`,practiceCategory===c.id?'cat-button active':'cat-button')).join('')}</div>`;}
function timeSummary(t){return t.patterns.length?t.patterns.map(p=>`${p}人：${D.secondsText(t.totals[p].seconds)}`).join(' / '):D.secondsText(t.seconds);}
function renderPracticeSelect(){if(!practiceDraft)return shell('練習メニュー','operations','<p class="empty">メニュー表を選択してください</p>','practice');const d=practiceDraft,menus=sortedTrainingMenus(state.training.menus.filter(m=>practiceCategory==='all'||m.categoryId===practiceCategory));const empty=edit('training')?`<div class="training-empty"><p>この分類にはメニューがありません</p><a class="secondary empty-action" href="#menu-edit">メニューを追加</a></div>`:'<p class="empty">この分類にはメニューがありません</p>';return shell('メニュー表作成','operations',`<div class="practice-progress" aria-label="作成の進行状況"><span class="active">1 メニュー</span><span>2 セット</span><span>3 出力</span></div>${practicePicker('練習日',d.eventId)}${field('メニュー表の名前','practiceTitle',d.title,'text','maxlength="200"')}${categoriesTabs()}<div class="training-select-list">${menus.map(m=>{const ix=d.rows.findIndex(r=>r.menuId===m.id);return `<button class="row practice-choice ${ix>=0?'selected':''}" data-act="practice-select-menu" data-id="${m.id}" aria-pressed="${ix>=0?'true':'false'}"><span class="selection-order ${ix>=0?'on':''}">${ix>=0?ix+1:''}</span><span class="row-main"><span class="row-title">${esc(m.name)}</span><span class="row-sub block">${D.secondsText(m.seconds)} / ${m.requiresSets?'セットあり':'1回のみ'}</span></span></button>`}).join('')||empty}</div><div class="sticky-action">${action('practice-next',d.rows.length?`次へ（${d.rows.length}件）`:'メニューを選択',d.rows.length?'':'disabled','primary full')}</div>`,'practice',action('practice-draft-save','下書き','','text-btn'));}
function setsControl(ix,p,value){return `<div class="set-control">${action('practice-step','−',`data-index="${ix}" data-pattern="${p}" data-step="-1" aria-label="${ix+1}番 ${p}人を減らす"`,'')}<input type="number" min="0" max="999" value="${value}" data-set-index="${ix}" data-pattern="${p}" aria-label="${ix+1}番 ${p}人のセット数">${action('practice-step','＋',`data-index="${ix}" data-pattern="${p}" data-step="1" aria-label="${ix+1}番 ${p}人を増やす"`,'')}</div>`;}
function renderPracticeSets(){const d=practiceDraft;if(!d)return shell('練習メニュー','operations','<p class="empty">メニュー表を選択してください</p>','practice');let t;try{t=D.trainingTotals(d.rows,d.patterns)}catch(err){return shell('練習メニュー','operations',esc(err.message),'practice-select');}const changed=d.eventId&&JSON.stringify(d.context)!==JSON.stringify(sessionInfo(d.eventId));const tooLong=d.context?.minutes!==null&&d.context?.minutes!==undefined&&t.patterns.some(p=>t.totals[p].seconds>d.context.minutes*60);return shell('セット数・人数','operations',`<div class="practice-progress" aria-label="作成の進行状況"><span>1 メニュー</span><span class="active">2 セット</span><span>3 出力</span></div><h2>${esc(d.title)}</h2>${d.context?`<div class="session-compact">${sessionSummary(d.context)}</div>`:''}${changed?`<div class="warning">予定・出欠が変更されています ${action('practice-refresh','反映')}</div>`:''}<div class="section-head"><span class="small muted">比較する人数を2つまで選択</span>${action('practice-patterns',d.patterns.map(p=>p+'人').join(' / ')||'未選択','','text-btn')}</div><table class="set-table"><thead><tr><th>メニュー</th>${d.patterns.map(p=>`<th>${p}人</th>`).join('')}</tr></thead><tbody>${d.rows.map((r,i)=>`<tr><td><div class="set-name">${esc(r.name)}</div><div class="row-sub">${D.secondsText(r.seconds)} / ${r.requiresSets?'1set・1人':'1回のみ'}</div><div class="reorder">${action('practice-order','↑',`data-index="${i}" data-step="-1" ${i===0?'disabled':''} aria-label="${i+1}番を上へ"`,'')}${action('practice-order','↓',`data-index="${i}" data-step="1" ${i===d.rows.length-1?'disabled':''} aria-label="${i+1}番を下へ"`,'')}${action('practice-remove','×',`data-index="${i}" aria-label="${i+1}番を外す"`,'')}</div></td>${r.requiresSets?d.patterns.map(p=>`<td>${setsControl(i,p,r.sets[p]??0)}</td>`).join(''):`<td colspan="${Math.max(d.patterns.length,1)}"><span class="once-pill">1回のみ</span></td>`}</tr>`).join('')}</tbody><tfoot><tr><th>合計人set</th>${d.patterns.map(p=>`<td>${t.totals[p].peopleSets} 人set</td>`).join('')}</tr></tfoot></table><div class="total-time pattern-times"><span>所要時間</span><div>${t.patterns.map(p=>`<strong><small>${p}人</small>${D.secondsText(t.totals[p].seconds)}</strong>`).join('')}</div></div>${t.mismatch?'<div class="warning">人数パターンごとに、メニュー別の人setが一致していません。</div>':''}${tooLong?'<div class="warning">練習時間を超える人数パターンがあります。</div>':''}<div class="form-actions">${action('practice-preview','画像を確認','','primary full')}${action('practice-save','表を保存','','secondary full')}</div>`,'practice-select');}
renderPracticeSaved=function(){const hist=[...state.training.history].sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''));const cards=hist.map(h=>{let src='';try{src=drawTraining(h.snapshot).toDataURL('image/png')}catch{}const when=h.createdAt?new Date(h.createdAt).toLocaleString('ja-JP'):'';return `<article class="training-history-card compact"><button class="training-history-open" data-act="practice-history-open" data-id="${h.id}" aria-label="${esc(h.title||'練習メニュー')}を開く"><span class="training-history-thumb">${src?`<img src="${src}" alt="">`:'<span class="empty-thumb">画像</span>'}</span><span class="training-history-copy"><strong>${esc(h.title||'練習メニュー')}</strong><small>${esc(when)}</small></span>${icon('chev','chev')}</button>${practiceHistoryEdit&&edit('training')?action('practice-history-delete','削除',`data-id="${h.id}"`,'text-btn danger-button history-delete'):''}</article>`}).join('');const empty=edit('training')?`<div class="training-empty"><p>履歴がありません</p><a class="secondary empty-action" href="#practice-new">メニュー表を作成</a></div>`:'<p class="empty">履歴がありません</p>';const sheets=[...state.training.sheets].sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));const saved=sheets.length?`<details class="advanced saved-practice-details"><summary>保存したメニュー表（${sheets.length}件）</summary><div class="saved-practice-list">${sheets.map(x=>`<a class="row" href="#practice-sheet/${x.id}"><span class="row-main"><span class="row-title">${esc(x.title)}</span><span class="row-sub block">${x.updatedAt?esc(new Date(x.updatedAt).toLocaleString('ja-JP')):''}</span></span>${icon('chev','chev')}</a>`).join('')}</div></details>`:'';return shell('練習メニュー履歴','operations',(cards||empty)+saved,'practice',edit('training')?action('practice-history-edit-toggle',practiceHistoryEdit?'完了':'編集','','text-btn'):'');};
function renderPracticeSheet(id){const s=state.training.sheets.find(s=>s.id===id);if(!s)return shell('練習メニュー','operations','見つかりません','practice-saved');const t=D.trainingTotals(s.rows,s.patterns);return shell('練習メニュー','operations',`<h2 class="detail-title">${esc(s.title)}</h2>${s.context?`<div class="session-compact">${sessionSummary(s.context)}</div>`:''}<table class="set-table preview"><thead><tr><th>種目</th>${s.patterns.map(p=>`<th>${p}人</th>`).join('')}</tr></thead><tbody>${s.rows.map(r=>`<tr><td><div>${esc(r.name)}</div><div class="row-sub">${D.secondsText(r.seconds)} / ${r.requiresSets?'1人・1セット':'1回'}</div></td>${r.requiresSets?s.patterns.map(p=>`<td>${r.sets[p]||0} set</td>`).join(''):`<td colspan="${Math.max(1,s.patterns.length)}">1回</td>`}</tr>`).join('')}</tbody><tfoot><tr><th>合計人set</th>${s.patterns.map(p=>`<td>${t.totals[p].peopleSets} 人set</td>`).join('')}</tr></tfoot></table><div class="total-time pattern-times"><span>所要時間</span><div>${t.patterns.map(p=>`<strong><small>${p}人</small>${D.secondsText(t.totals[p].seconds)}</strong>`).join('')}</div></div><div class="form-actions">${action('practice-image','画像出力',`data-id="${s.id}"`,'secondary full')}${edit('training')?action('practice-copy','複製',`data-id="${s.id}"`,'secondary full'):''}</div>`,'practice-saved',edit('training')?action('practice-edit','編集',`data-id="${s.id}"`):'');}
function renderPracticeCategories(){const rows=state.training.categories.map(c=>{const used=state.training.menus.filter(m=>m.categoryId===c.id).length;if(!practiceCategoryEdit)return `<button class="training-category-card" data-act="category-edit" data-id="${c.id}"><span class="row-main"><span class="row-title">${esc(c.name)}</span><span class="row-sub">登録メニュー ${used}件</span></span>${icon('chev','chev')}</button>`;return `<div class="training-category-card edit-mode" data-category-id="${c.id}"><button class="menu-drag-handle" data-category-drag="${c.id}" aria-label="${esc(c.name)}を並び替える">☰</button><span class="row-main"><span class="row-title">${esc(c.name)}</span><span class="row-sub">登録メニュー ${used}件</span></span>${action('category-delete','削除',`data-id="${c.id}"`,'text-btn danger-button')}</div>`}).join('')||'<p class="empty">分類はありません</p>';const add=edit('training')?`<button class="training-category-card add-card" data-act="category-add"><span class="row-main"><span class="row-title">＋ 分類を追加</span></span>${icon('chev','chev')}</button>`:'';return shell('分類一覧','operations',add+`<div class="training-category-list">${rows}</div>`,'practice',edit('training')?action('category-edit-toggle',practiceCategoryEdit?'完了':'編集','','text-btn'):'');}
function renderMenuList(){const menus=sortedTrainingMenus(state.training.menus.filter(m=>practiceCategory==='all'||m.categoryId===practiceCategory));const controls=`<div class="section-head"><span class="small muted">${menus.length}件</span>${edit('training')?action('menu-reorder-toggle',practiceReorder?'完了':'編集','','text-btn'):''}</div>`;const rows=menus.map(m=>{const cat=esc(state.training.categories.find(c=>c.id===m.categoryId)?.name||'未分類'),meta=`${cat} / ${D.secondsText(m.seconds)} / ${m.requiresSets?'セットあり':'1回のみ'}`;if(!practiceReorder)return `<a class="training-menu-card" href="#menu-edit/${m.id}"><div class="row-main"><div class="row-title">${esc(m.name)}</div><div class="row-sub">${meta}</div></div>${icon('chev','chev')}</a>`;return `<div class="training-menu-card edit-mode" data-menu-id="${m.id}" data-category-id="${m.categoryId}"><button class="menu-drag-handle" data-menu-drag="${m.id}" aria-label="${esc(m.name)}を並び替える">☰</button><div class="row-main"><div class="row-title">${esc(m.name)}</div><div class="row-sub">${meta}</div></div>${action('menu-delete','削除',`data-id="${m.id}"`,'text-btn danger-button')}</div>`}).join('')||(edit('training')?`<div class="training-empty"><p>メニューがありません</p><a class="secondary empty-action" href="#menu-edit">メニューを追加</a></div>`:'<p class="empty">メニューがありません</p>');return shell('メニュー一覧','operations',categoriesTabs()+controls+`<div class="training-menu-list">${rows}</div>`+`<hr class="rule">${edit('training')?action('training-import','以前のデータを取り込む','','text-btn'):''}`,'practice',edit('training')?`<a class="icon-btn" href="#menu-edit" aria-label="メニューを追加">${icon('plus')}</a>`:'');}


function clearCategoryDropTargets(){document.querySelectorAll('.training-category-card.drop-before,.training-category-card.drop-after').forEach(x=>x.classList.remove('drop-before','drop-after'));}
function cleanupCategoryDrag(){if(!categoryDrag)return;clearCategoryDropTargets();categoryDrag.card?.classList.remove('dragging');document.body.classList.remove('menu-is-dragging');try{if(categoryDrag.handle?.hasPointerCapture?.(categoryDrag.pointerId))categoryDrag.handle.releasePointerCapture(categoryDrag.pointerId)}catch{}categoryDrag=null;}
function reorderCategoryRelative(sourceId,targetId,position){const list=[...state.training.categories],from=list.findIndex(c=>c.id===sourceId);let to=list.findIndex(c=>c.id===targetId);if(from<0||to<0||sourceId===targetId)return false;checkpoint();const [item]=list.splice(from,1);to=list.findIndex(c=>c.id===targetId);if(position==='after')to++;list.splice(to,0,item);state.training.categories=list;persist();render();toast(`${item.name}を${to+1}番目に移動しました`,true);return true;}
function clearMenuDropTargets(){document.querySelectorAll('.training-menu-card.drop-before,.training-menu-card.drop-after').forEach(x=>x.classList.remove('drop-before','drop-after'));}
function cleanupMenuDrag(){if(!menuDrag)return;clearMenuDropTargets();menuDrag.card?.classList.remove('dragging');document.body.classList.remove('menu-is-dragging');try{if(menuDrag.handle?.hasPointerCapture?.(menuDrag.pointerId))menuDrag.handle.releasePointerCapture(menuDrag.pointerId)}catch{}menuDrag=null;}
function reorderMenuRelative(sourceId,targetId,position){const source=state.training.menus.find(m=>m.id===sourceId),target=state.training.menus.find(m=>m.id===targetId);if(!source||!target||source.id===target.id||source.categoryId!==target.categoryId)return false;const siblings=sortedTrainingMenus(state.training.menus.filter(m=>m.categoryId===source.categoryId)),ids=siblings.map(m=>m.id).filter(id=>id!==sourceId);let at=ids.indexOf(targetId);if(at<0)return false;if(position==='after')at++;ids.splice(at,0,sourceId);ids.forEach((id,i)=>{const m=state.training.menus.find(x=>x.id===id);if(m)m.order=i;});persist();render();return true;}
document.addEventListener('pointerdown',ev=>{const handle=ev.target.closest('[data-category-drag]');if(!handle||!practiceCategoryEdit||getRoute()[0]!=='practice-categories'||ev.button!==0)return;const card=handle.closest('.training-category-card[data-category-id]');if(!card)return;ev.preventDefault();categoryDrag={pointerId:ev.pointerId,sourceId:card.dataset.categoryId,startX:ev.clientX,startY:ev.clientY,active:false,targetId:null,position:null,handle,card};try{handle.setPointerCapture(ev.pointerId)}catch{}},{capture:true});
document.addEventListener('pointermove',ev=>{if(!categoryDrag||ev.pointerId!==categoryDrag.pointerId)return;if(!categoryDrag.active&&Math.hypot(ev.clientX-categoryDrag.startX,ev.clientY-categoryDrag.startY)>6){categoryDrag.active=true;categoryDrag.card.classList.add('dragging');document.body.classList.add('menu-is-dragging');}if(!categoryDrag.active)return;ev.preventDefault();clearCategoryDropTargets();const target=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('.training-category-card[data-category-id]');if(!target||target.dataset.categoryId===categoryDrag.sourceId){categoryDrag.targetId=null;categoryDrag.position=null;return;}const rect=target.getBoundingClientRect(),position=ev.clientY<rect.top+rect.height/2?'before':'after';target.classList.add(position==='before'?'drop-before':'drop-after');categoryDrag.targetId=target.dataset.categoryId;categoryDrag.position=position;},{capture:true,passive:false});
document.addEventListener('pointerup',ev=>{if(!categoryDrag||ev.pointerId!==categoryDrag.pointerId)return;const {active,sourceId,targetId,position}=categoryDrag;cleanupCategoryDrag();if(active&&targetId&&position)reorderCategoryRelative(sourceId,targetId,position);},{capture:true});
document.addEventListener('pointercancel',ev=>{if(categoryDrag&&ev.pointerId===categoryDrag.pointerId)cleanupCategoryDrag();},{capture:true});
document.addEventListener('pointerdown',ev=>{const handle=ev.target.closest('[data-menu-drag]');if(!handle||!practiceReorder||getRoute()[0]!=='menu-list'||ev.button!==0)return;const card=handle.closest('.training-menu-card[data-menu-id]');if(!card)return;ev.preventDefault();menuDrag={pointerId:ev.pointerId,sourceId:card.dataset.menuId,categoryId:card.dataset.categoryId,startX:ev.clientX,startY:ev.clientY,x:ev.clientX,y:ev.clientY,active:false,targetId:null,position:null,handle,card};try{handle.setPointerCapture(ev.pointerId)}catch{}},{capture:true});
document.addEventListener('pointermove',ev=>{if(!menuDrag||ev.pointerId!==menuDrag.pointerId)return;menuDrag.x=ev.clientX;menuDrag.y=ev.clientY;if(!menuDrag.active&&Math.hypot(ev.clientX-menuDrag.startX,ev.clientY-menuDrag.startY)>6){menuDrag.active=true;menuDrag.card.classList.add('dragging');document.body.classList.add('menu-is-dragging');}if(!menuDrag.active)return;ev.preventDefault();clearMenuDropTargets();const target=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('.training-menu-card[data-menu-id]');if(!target||target.dataset.menuId===menuDrag.sourceId||target.dataset.categoryId!==menuDrag.categoryId){menuDrag.targetId=null;menuDrag.position=null;return;}const rect=target.getBoundingClientRect(),position=ev.clientY<rect.top+rect.height/2?'before':'after';target.classList.add(position==='before'?'drop-before':'drop-after');menuDrag.targetId=target.dataset.menuId;menuDrag.position=position;},{capture:true,passive:false});
document.addEventListener('pointerup',ev=>{if(!menuDrag||ev.pointerId!==menuDrag.pointerId)return;const {active,sourceId,targetId,position}=menuDrag;cleanupMenuDrag();if(active&&targetId&&position)reorderMenuRelative(sourceId,targetId,position);},{capture:true});
document.addEventListener('pointercancel',ev=>{if(menuDrag&&ev.pointerId===menuDrag.pointerId)cleanupMenuDrag();},{capture:true});
function renderMenuEdit(id){const m=state.training.menus.find(x=>x.id===id)||{id:'',name:'',categoryId:state.training.categories[0]?.id,seconds:60,requiresSets:true};const title=id?'メニュー編集':'メニュー追加';return header(title,'menu-list')+`<main class="content"><form id="edit-form" data-form="menu" data-id="${id||''}"><label class="field"><span class="label">名前</span><input name="name" value="${esc(m.name)}" required maxlength="150" aria-describedby="menu-name-error"><span class="field-error" id="menu-name-error"></span></label><label class="field"><span class="label">分類</span><select name="categoryId" required aria-describedby="menu-category-error">${state.training.categories.map(c=>`<option value="${c.id}" ${c.id===m.categoryId?'selected':''}>${esc(c.name)}</option>`).join('')}</select><span class="field-error" id="menu-category-error"></span></label>${action('category-add','分類を追加','','text-btn')}<fieldset class="field method-field"><legend class="label">実施方法</legend><div class="method-options"><label class="method-option"><input type="radio" name="requiresSets" value="true" ${m.requiresSets?'checked':''}><span>セットあり</span></label><label class="method-option"><input type="radio" name="requiresSets" value="false" ${!m.requiresSets?'checked':''}><span>1回のみ</span></label></div></fieldset><div class="field"><span class="label">時間</span><div class="inline-fields"><label class="field compact-field"><input name="minutes" type="number" value="${Math.floor(m.seconds/60)}" min="0" max="1440" step="1" inputmode="numeric" aria-label="分" aria-describedby="menu-time-error"><span class="input-unit">分</span></label><label class="field compact-field"><input name="seconds" type="number" value="${m.seconds%60}" min="0" max="59" step="1" inputmode="numeric" aria-label="秒" aria-describedby="menu-time-error"><span class="input-unit">秒</span></label></div><span class="field-error" id="menu-time-error"></span></div><div class="form-actions"><a class="secondary full" href="#menu-list">戻る</a><button class="primary full" type="submit">${id?'保存する':'追加する'}</button></div></form></main>`+nav('operations');}
function saveSheet(d){if(!d.title.trim()||!d.rows.length)throw Error('種目を選択してください');D.trainingTotals(d.rows,d.patterns);const saved=clone(d);saved.updatedAt=new Date().toISOString();saved.updatedBy=state.currentUser;const ix=state.training.sheets.findIndex(s=>s.id===d.id);if(ix<0)state.training.sheets.push(saved);else state.training.sheets[ix]=saved;persist();return saved;}
function measureLines(c,text,max){const out=[];for(const para of String(text).split('\n')){let line='';for(const ch of para){if(c.measureText(line+ch).width>max&&line){out.push(line);line='';}line+=ch;}out.push(line);}return out;}
function imageCanvas(w,h){const cv=document.createElement('canvas');cv.width=w*2;cv.height=h*2;const c=cv.getContext('2d');c.scale(2,2);c.fillStyle='#fff';c.fillRect(0,0,w,h);c.fillStyle='#18211c';c.font='16px "Noto Sans CJK JP", sans-serif';return [cv,c];}
function drawTraining(s){const t=D.trainingTotals(s.rows,s.patterns),w=820;const rows=s.rows.map(r=>({...r,lines:Math.ceil(r.name.length/18)}));const h=235+rows.reduce((v,r)=>v+Math.max(62,r.lines*26+24),0);const [cv,c]=imageCanvas(w,h);c.font='600 25px "Noto Sans CJK JP", sans-serif';const title=measureLines(c,s.title,w-60);title.forEach((l,i)=>c.fillText(l,30,40+i*30));c.font='14px "Noto Sans CJK JP", sans-serif';let y=52+title.length*30;c.fillStyle='#717a74';if(s.context){c.fillText(`${jpDate(s.context.date)} ${s.context.venue}　${s.context.participants}人${s.context.courts?' / '+s.context.courts+'面':''}`,30,y);y+=28;}c.fillText(`所要時間　${timeSummary(t)}`,30,y);y+=22;c.fillText(`合計人set　${t.patterns.map(p=>p+'人：'+t.totals[p].peopleSets).join(' / ')}`,30,y);y+=26;c.fillStyle='#edf7f0';c.fillRect(30,y,w-60,40);c.fillStyle='#18211c';c.font='600 15px "Noto Sans CJK JP", sans-serif';c.fillText('種目',45,y+26);s.patterns.forEach((p,i)=>c.fillText(p+'人',520+i*100,y+26));y+=40;for(const r of rows){const rh=Math.max(62,r.lines*26+24);c.strokeStyle='#e5e9e6';c.strokeRect(30,y,w-60,rh);c.fillStyle='#18211c';c.font='16px "Noto Sans CJK JP", sans-serif';measureLines(c,r.name,430).forEach((l,i)=>c.fillText(l,45,y+27+i*25));c.font='12px "Noto Sans CJK JP", sans-serif';c.fillStyle='#717a74';c.fillText(`${D.secondsText(r.seconds)} / ${r.requiresSets?'1人・1セット':'1回'}`,45,y+rh-10);c.fillStyle='#18211c';c.font='14px "Noto Sans CJK JP", sans-serif';s.patterns.forEach((p,i)=>c.fillText(r.requiresSets?`${r.sets[p]||0} set`:'1回',520+i*100,y+29));y+=rh;}return cv;}
async function shareCanvas(cv,filename){const blob=await new Promise(r=>cv.toBlob(r,'image/png'));if(!blob)throw Error('画像を生成できませんでした');const file=new File([blob],filename,{type:'image/png'});if(navigator.canShare?.({files:[file]})&&navigator.share){try{await navigator.share({files:[file]});return}catch(err){if(err.name==='AbortError')return;}}const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function imagePreview(cv,name){previewCanvas={cv,name};previewPracticeSource=null;modal('画像',`<img class="image-preview" alt="生成した画像" src="${cv.toDataURL('image/png')}"><div class="form-actions">${action('image-share','共有・保存','','primary full')}</div>`);}
function trainingImagePreview(source,{allowHistory=true}={}){if(!source)return;previewPracticeSource=clone(source);previewPracticeHistorySaved=!allowHistory;const cv=drawTraining(previewPracticeSource),name=(previewPracticeSource.title||'練習メニュー')+'.png';previewCanvas={cv,name};modal('画像プレビュー',`<div class="practice-progress preview-progress"><span>1 メニュー</span><span>2 セット</span><span class="active">3 出力</span></div><img class="image-preview" alt="生成した練習メニュー画像" src="${cv.toDataURL('image/png')}">${allowHistory&&edit('training')?'<label class="history-option"><input type="checkbox" id="practice-history-on-save" checked><span>履歴にも追加する</span></label>':''}<div class="training-preview-actions">${action('image-download','画像を保存','','primary')}${action('image-close','閉じる','','secondary')}</div>`);}
function downloadCanvas(cv,name){if(!cv)return;const a=document.createElement('a');a.href=cv.toDataURL('image/png');a.download=name||'画像.png';document.body.appendChild(a);a.click();a.remove();}
function trainingHistoryItem(id){return state.training.history.find(h=>h.id===id);}
function drawCalendar(withExec=false){
 const y=ui.calendarYear,m=ui.calendarMonth,offset=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),weeks=Math.ceil((offset+days)/7),cw=155,w=cw*7+48;
 const probe=document.createElement('canvas').getContext('2d');probe.font='13px "Noto Sans CJK JP", sans-serif';
 const cells=Array.from({length:weeks*7},(_,i)=>{const day=i-offset+1;if(day<1||day>days)return {day:null,blocks:[]};const dt=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;return {day,blocks:D.calendarItems(state,dt,withExec).map(item=>({kind:item.kind,colorId:event(item.id)?.colorId,lines:[...(item.kind!=='club'&&item.time?[item.time+(item.end?'–'+item.end:'')]:[]),...measureLines(probe,item.title,cw-18)]}))};});
 const rh=Array.from({length:weeks},(_,wi)=>Math.max(100,...cells.slice(wi*7,wi*7+7).map(cell=>42+cell.blocks.reduce((a,b)=>a+b.lines.length*18+10,0))));const h=100+rh.reduce((a,b)=>a+b,0);if(h>12000)throw Error('予定が多すぎるため、この月を1枚に出力できません');
 const [cv,c]=imageCanvas(w,h);c.font='600 24px "Noto Sans CJK JP", sans-serif';c.fillText(`${y}年${m+1}月　${withExec?'幹部予定も表示':'部活予定'}`,24,42);c.font='15px "Noto Sans CJK JP", sans-serif';'日月火水木金土'.split('').forEach((v,i)=>c.fillText(v,24+i*cw+cw/2,80));let py=96;
 for(let wi=0;wi<weeks;wi++){for(let col=0;col<7;col++){const cell=cells[wi*7+col],x=24+col*cw;c.strokeStyle='#dce5df';c.strokeRect(x,py,cw,rh[wi]);if(!cell.day)continue;c.fillStyle='#18211c';c.font='600 15px "Noto Sans CJK JP", sans-serif';c.fillText(String(cell.day),x+10,py+24);let ty=py+48;for(const block of cell.blocks){c.fillStyle=typeof calColor==='function'?calColor(block):(block.kind==='club'?'#14813b':'#455969');c.fillRect(x+4,ty-15,cw-8,block.lines.length*18+4);c.fillStyle='#242522';c.font='13px "Noto Sans CJK JP", sans-serif';for(const line of block.lines){c.fillText(line,x+9,ty);ty+=18;}ty+=10;}}py+=rh[wi];}return cv;
}
/* Carpool's single data source, monthly snapshots, explicit per-leg adjustments. */
function lockedPlan(id){return state.settlements.some(s=>s.locked&&s.planIds.includes(id));}
missing=function(p,leg){return D.missing(state,p,leg).map(person);};
invalid=function(p){return D.planErrors(state,p);};
moveMember=function(id,mid,dest,leg){const p=plan(id);if(!p)return {ok:false,error:'配車がありません'};if(!edit('plans'))return {ok:false,error:'閲覧のみです'};if(lockedPlan(id))return {ok:false,error:'精算確定済みです'};try{const updated=D.move(state,p,mid,{...dest,newId:UID()},leg||legOf(p));checkpoint();Object.assign(p,updated);ui.selectedPerson=null;persist();return {ok:true};}catch(err){return {ok:false,error:err.message};}};
const oldRenderCar=renderCar;
renderCar=function(id){const p=plan(id);if(!p)return shell('配車','operations','見つかりません','carpools');let html=oldRenderCar(id);if(event(p.eventId)?.cancelled)html=html.replace('<div class="car-meta">','<div class="warning">予定は中止されています</div><div class="car-meta">');if(!p.enabled[legOf(p)])html=html.replace('<div class="car-meta">','<div class="warning">この片道は対象外です</div><div class="car-meta">');if(!edit('plans')||lockedPlan(id)){html=html.replaceAll('data-act="register-car"','disabled data-act="register-car"').replaceAll('data-act="new-car"','disabled data-act="new-car"').replaceAll('data-act="copy-open"','disabled data-act="copy-open"').replaceAll('data-act="car-menu"','disabled data-act="car-menu"');}return html;};
copyPlan=function(srcid,dstid){const src=plan(srcid),dst=plan(dstid);if(!src||!dst||src===dst||lockedPlan(dstid)||!edit('plans'))return {ok:false,removed:0};checkpoint();const removed=new Set();for(const leg of ['outbound','return']){dst.legs[leg]=src.legs[leg].map(c=>{const valid=mid=>{const yes=D.participating(state,dst.eventId,mid);if(!yes)removed.add(mid);return yes;};return {id:UID(),pickup:c.pickup,driver:c.driver&&valid(c.driver)?c.driver:null,riders:c.riders.filter(valid)};});dst.need[leg]={};dst.enabled[leg]=src.enabled[leg];}dst.linked=src.linked;if(dst.linked)dst.legs.return=clone(dst.legs.outbound);dst.status='draft';if(dst.unitYen===undefined)dst.unitYen=state.settings.unitYen;dst.sourcePlanId=src.id;dst.version++;dst.adjustments={};dst.legDates=dst.legDates||{outbound:event(dst.eventId).date,return:event(dst.eventId).endDate||event(dst.eventId).date};dst.notifications=dst.notifications||[...state.settings.reminders];persist();return {ok:true,removed:removed.size};};
carOptions=function(id){const p=plan(id),e=event(p.eventId);modal('配車設定',`<form data-form="car-options2" data-id="${id}"><div class="row"><span class="row-main">往復同じ</span>${action(p.linked?'split-apply':'merge-apply',p.linked?'分ける':'まとめる',`data-id="${id}"`)}</div><div class="inline-fields">${field('行きの利用日','outboundDate',p.legDates?.outbound||e.date,'date','required')}${field('帰りの利用日','returnDate',p.legDates?.return||e.endDate||e.date,'date','required')}</div>${!p.linked?`<div class="options">${['outbound','return'].map(l=>`<label class="option"><input type="checkbox" name="leg" value="${l}" ${p.enabled[l]?'checked':''}>${l==='outbound'?'行き':'帰り'}</label>`).join('')}</div>`:''}<div class="field-gap"></div>${field('片道1回の料金（円）','unitYen',p.unitYen??'','number','min="0" max="1000000" step="1"')}${notifications(p.notifications||state.settings.reminders)}<div class="form-actions"><button class="primary full" type="submit" ${!edit('plans')||lockedPlan(id)?'disabled':''}>保存</button></div></form>`);};
settlementLines=function(month=ui.settlementMonth){return D.settlement(state,month);};
function currentStatement(){return state.settlements.filter(x=>x.month===ui.settlementMonth&&x.locked).at(-1);}
renderSettlement=function(){const snap=currentStatement(),lines=snap?snap.lines:settlementLines();return shell('月次精算','operations',`<div class="month-head">${action('settlement-month','‹','data-dir="-1" aria-label="前月"','icon-btn')}<h2>${ui.settlementMonth.replace('-','年')}月</h2>${action('settlement-month','›','data-dir="1" aria-label="翌月"','icon-btn')}</div>${snap?'<div class="section-head"><span class="small green">確定済み</span></div>':''}${lines.map(l=>`<button class="row" data-act="settlement-detail2" data-rider="${l.rider}" data-driver="${l.driver}"><span class="row-main">${esc(l.riderName||pName(l.rider))} → ${esc(l.driverName||pName(l.driver))}</span><strong>${l.unset?'単価未設定':money(l.amount)}</strong>${icon('chev','chev')}</button>`).join('')||'<p class="empty">集計対象はありません</p>'}${lines.length?`<div class="row"><span class="row-main muted">合計</span><strong>${lines.some(l=>l.unset)?'単価未設定':money(lines.reduce((a,l)=>a+l.amount,0))}</strong></div>`:''}${edit('plans')?`<div class="form-actions">${action(snap?'statement-reopen':'statement-lock',snap?'確定を解除':'実際の利用を確認して確定',lines.length&&!lines.some(l=>l.unset)?'':'disabled','secondary full')}</div>`:''}<p class="note" style="margin-top:15px">乗車者から運転者へ直接支払う金額です。</p>`,'carpools');};
function settlementDetail(rider,driver){const snap=currentStatement(),l=(snap?snap.lines:settlementLines()).find(x=>x.rider===rider&&x.driver===driver);if(!l)return;modal(`${l.riderName||pName(rider)} → ${l.driverName||pName(driver)}`,`<strong class="overview-amount">${l.unset?'単価未設定':money(l.amount)}</strong>${l.details.map((x,i)=>`<button class="row" data-act="charge-edit" data-plan="${x.planId}" data-leg="${x.leg}" data-rider="${rider}" ${snap||!edit('plans')?'disabled':''}><div class="row-main">${jpDate(x.date)} ${x.leg==='outbound'?'行き':'帰り'}<div class="row-sub">${x.count}回 × ${x.unitYen??'未設定'}円</div></div><span>${x.amount===null?'未設定':money(x.amount)}</span>${!snap?icon('chev','chev'):''}</button>`).join('')}`);}
function chargeEdit(pid,leg,mid){const p=plan(pid),a=p.adjustments?.[leg+'|'+mid]||{};modal('精算の調整',`<form data-form="charge" data-id="${pid}" data-leg="${leg}" data-rider="${mid}"><p style="margin-bottom:20px">${esc(pName(mid))}　${leg==='outbound'?'行き':'帰り'}</p><div class="inline-fields">${field('回数','count',a.count??1,'number','required min="0" max="999"')}${field('単価（円）','unitYen',a.unitYen??p.unitYen??'','number','min="0" max="1000000"')}</div>${field('理由','reason',a.reason||'','text','maxlength="200"')}<label class="option"><input type="checkbox" name="excluded" ${a.excluded?'checked':''}>精算対象外</label><div class="form-actions"><button class="primary full">保存</button></div></form>`);}
// The share image is drawn from plan data, never from the editor screenshot.
drawCarCanvas=function(id){
 const p=plan(id),e=event(p.eventId),parts=tableParts(p),colW=168,pad=30,w=Math.max(520,60+Math.max(1,...parts.map(x=>x.cars.length))*colW),probe=document.createElement('canvas').getContext('2d');
 const font=(size,bold=false)=>`${bold?'600':'400'} ${size}px "Noto Sans CJK JP", sans-serif`;
 probe.font=font(22,true);const title=`${jpDate(e.date)}${e.endDate&&e.endDate!==e.date?'〜'+jpDate(e.endDate):''} ${eventVenue(e)?.name||e.title}${p.linked?'（往復）':''}`,titleLines=measureLines(probe,title,w-60);
 const blocks=parts.map(part=>{probe.font=font(18,true);const headers=part.cars.map(c=>measureLines(probe,pName(c.driver),colW-20));const hh=Math.max(48,...headers.map(ls=>ls.length*24+18));const rowCount=Math.max(1,...part.cars.map(c=>c.riders.length));probe.font=font(17);const cells=part.cars.map(c=>Array.from({length:rowCount},(_,i)=>c.riders[i]?measureLines(probe,pName(c.riders[i]),colW-20):[]));const rh=Array.from({length:rowCount},(_,i)=>Math.max(46,...cells.map(a=>a[i].length*24+18)));return {part,headers,hh,cells,rh};});
 const h=45+titleLines.length*31+blocks.reduce((sum,b)=>sum+40+b.hh+b.rh.reduce((a,c)=>a+c,0)+24,0);if(w>8000||h>12000)throw Error('画像にするデータが大きすぎます');const [cv,c]=imageCanvas(w,h);c.fillStyle='#18211c';c.font=font(22,true);titleLines.forEach((l,i)=>c.fillText(l,pad,38+i*31));let y=55+titleLines.length*31;
 for(const b of blocks){c.fillStyle='#3e5044';c.font=font(14);c.fillText(b.part.label+(p.linked?'':'（'+b.part.legLabel+'）'),pad,y);y+=16;b.part.cars.forEach((car,i)=>{const x=pad+i*colW;c.fillStyle='#edf7f0';c.fillRect(x,y,colW,b.hh);c.strokeStyle='#dce5df';c.strokeRect(x,y,colW,b.hh);c.fillStyle='#18211c';c.textAlign='center';c.font=font(18,true);b.headers[i].forEach((line,j)=>c.fillText(line,x+colW/2,y+30+j*24));let cy=y+b.hh;c.font=font(17);b.rh.forEach((rh,k)=>{c.strokeRect(x,cy,colW,rh);b.cells[i][k].forEach((line,j)=>c.fillText(line,x+colW/2,cy+29+j*24));cy+=rh;});c.textAlign='left';});y+=b.hh+b.rh.reduce((a,r)=>a+r,0)+48;}return cv;
};
/* Settings and actual account/group membership are separate from roster entries. */
renderSettings=function(){return shell('設定','settings',`<div class="section"><h2>${esc(state.group.name)}</h2><p class="row-sub">${esc(oName(state.currentUser))}${ctx.mode==='demo'?'　端末内デモ':''}</p></div>`+entry('グループ','group','people')+entry('部員','members','people')+entry('運営メンバー','operators','people')+entry('担当・権限','roles','shield')+entry('通知','notification-settings','bell')+entry('配車設定','car-settings','car')+`<hr class="rule">${action('backup-export','バックアップを書き出す','','row')}${ctx.mode==='demo'?action('demo-reset2','サンプルをリセット','','row danger-button'):action('logout2','ログアウト','','row danger-button')}`);};
renderGroup=function(){return shell('グループ','settings',`<h2>${esc(state.group.name)}</h2><p class="row-sub" style="margin:12px 0">オーナー ${esc(oName(state.ownerId))}</p>${action('group-picker','グループを切り替える','','row')}${own()?`<form data-form="group2">${field('グループ名','name',state.group.name,'text','required maxlength="100"')}<button class="primary" type="submit">保存</button></form>`:''}`,'settings');};
renderOperators=function(){return shell('運営メンバー','settings',state.operators.map(o=>`<button class="row" data-act="operator-menu" data-id="${o.id}"><span class="row-main">${esc(o.name)}</span><span class="small muted">${o.id===state.ownerId?'オーナー':''}</span>${own()?icon('chev','chev'):''}</button>`).join('')+(own()?`<div class="form-actions">${action('invite2','招待','','secondary full')}</div>`:''),'settings');};
renderRoles=function(){return shell('担当・権限','settings',Object.entries(state.roles).map(([name,ids])=>`<button class="row" data-act="role-edit" data-name="${esc(name)}" ${own()?'':'disabled'}><span class="row-main">${esc(name)}</span><span class="small">${ids.length?esc(aNames(ids)):'未設定'}</span>${own()?icon('chev','chev'):''}</button>`).join('')+'<p class="note" style="margin-top:20px">運営メンバーは閲覧、担当者は編集。</p>','settings');};
renderNotificationSettings=function(){return formShell('通知','settings','notifications',`<div class="row"><span class="row-main">この端末の通知</span>${action('enable-push','有効にする')}</div><p class="note" style="margin:12px 0 24px">${ctx.mode==='demo'?'デモでは通知を送信しません。':ctx.pushConfig.push?'ホーム画面から開き、通知を許可してください。':'通知は準備中です。'}</p>`+notifications(state.settings.reminders)+'<p class="note">時刻なし予定は9:00を基準にします。</p>','settings');};
renderCarSettings=function(){return formShell('配車設定','settings','carsettings',field('片道1回の料金（円）','unitYen',state.settings.unitYen??'','number','min="0" max="1000000" step="1"')+'<p class="note">往復は2回。過去の料金は変更しません。</p><hr class="rule">'+notifications(state.settings.reminders),'settings');};
function authScreen(){document.body.classList.remove('wide');return `<div class="auth-screen"><h1>部活運営</h1>${segments([['login','ログイン'],['register','登録']],ctx.authTab,'auth-tab')}<form data-form="auth">${ctx.authTab==='register'?field('名前','name','','text','required autocomplete="name"'):''}${field('メール','email','','email','required autocomplete="email"')}${field('パスワード','password','','password',`required minlength="10" maxlength="256" autocomplete="${ctx.authTab==='register'?'new-password':'current-password'}"`)}<button class="primary full" type="submit">${ctx.authTab==='login'?'ログイン':'登録'}</button></form><div class="form-actions">${action('start-demo','デモを開く','','secondary full')}</div></div>`;}
function groupScreen(){return header('グループ')+`<main class="content">${ctx.groups.map(g=>action('switch-group',`<span class="row-main">${esc(g.name)}</span>${icon('chev','chev')}`,`data-id="${g.id}"`,'row')).join('')}<form data-form="group-create" style="margin-top:28px">${field('グループ名','name','','text','required maxlength="100"')}<button class="primary full">グループを作成</button></form><form data-form="group-join" style="margin-top:28px">${field('招待コード','token',sessionStorage.getItem('club-invite')||'','text','required')}<button class="secondary full">招待から参加</button></form></main>`;}
function editableRoute(route){const maps={'event-edit':'events','task-edit':'tasks','task-add-from':'tasks','notice-edit':'notices','member-edit':'people','venue-edit':'venues','equipment-edit':'equipment','menu-edit':'training','practice-new':'training','practice-select':'training','practice-sets':'training','practice-categories':'training'};return !maps[route]||edit(maps[route]);}
render=function(){
 if(!ctx.ready)return;
 if(ctx.mode==='server'&&!ctx.user){document.getElementById('app').innerHTML=authScreen();return;}
 if(ctx.mode==='server'&&!ctx.base){document.getElementById('app').innerHTML=groupScreen();return;}
 const [r,id,extra]=getRoute();let html=null;if(r!=='menu-list'&&practiceReorder){practiceReorder=false;cleanupMenuDrag();}if(r!=='practice-categories'&&practiceCategoryEdit){practiceCategoryEdit=false;cleanupCategoryDrag();}if(r!=='practice-saved')practiceHistoryEdit=false;
 if(r==='legacy'){go('practice');return;}
 if(r==='group-open'){openDeepGroup(id,extra);return;}
 if(!editableRoute(r))html=shell('閲覧のみ','operations','<p class="empty">編集権限がありません</p>','operations');
 else if(r==='practice-new'){newPractice();return;}
 else if(r==='practice-select')html=renderPracticeSelect();
 else if(r==='practice-sets')html=renderPracticeSets();
 else if(r==='practice-sheet')html=renderPracticeSheet(id);
 else if(r==='practice-categories')html=renderPracticeCategories();
 else if(r==='menu-list')html=renderMenuList();
 else if(r==='menu-edit')html=renderMenuEdit(id);
 else if(r==='notice'&&!state.notices.some(n=>n.id===id&&noticeVisible(n)))html=shell('お知らせ','home','<p class="empty">表示できません</p>','notices');
 if(html!==null){document.body.classList.remove('wide');document.getElementById('app').innerHTML=html;}
 else origRender();
 // Module list links remain visible; unauthorized edit actions do not.
 if(!edit('tasks'))document.querySelectorAll('[href^="#task-edit"],[href^="#task-add-from"]').forEach(e=>e.remove());
 if(!edit('notices'))document.querySelectorAll('[href^="#notice-edit"]').forEach(e=>e.remove());
 if(!edit('training'))document.querySelectorAll('[href="#practice-new"],[href="#menu-edit"]').forEach(e=>e.remove());
 if(!edit('plans'))document.querySelectorAll('[href="#car-add"]').forEach(e=>e.remove());
 if(!edit('people'))document.querySelectorAll('[href="#member-edit"]').forEach(e=>e.remove());
 if(!edit('venues'))document.querySelectorAll('[href="#venue-edit"]').forEach(e=>e.remove());
 if(!edit('equipment'))document.querySelectorAll('[href="#equipment-edit"],[data-act="stock"]').forEach(e=>e.remove());
 if(!own()&&['notification-settings','car-settings'].includes(r))document.querySelector('button[form="edit-form"]')?.remove();
 if(ctx.conflict){const bar=document.createElement('div');bar.className='sync-error';bar.innerHTML=`${esc(ctx.conflict.message)} ${action('reload-server','再読込')} ${action('unsaved-export','未保存分を書出し')}`;document.getElementById('app').prepend(bar);}
};
let focusBefore=null;
modal=function(title,content){focusBefore=document.activeElement;origModal(title,content);setTimeout(()=>document.querySelector('.modal button,.modal input,.modal a')?.focus(),0);};
closeModal=function(){origClose();if(focusBefore?.isConnected)focusBefore.focus();focusBefore=null;};
document.addEventListener('keydown',ev=>{const m=document.querySelector('.modal');if(!m)return;if(ev.key==='Escape'){closeModal();ev.preventDefault();}if(ev.key==='Tab'){const a=[...m.querySelectorAll('button:not([disabled]),input:not([disabled]),select,textarea,a[href],summary')].filter(x=>x.getClientRects().length);if(!a.length)return;if(ev.shiftKey&&document.activeElement===a[0]){a.at(-1).focus();ev.preventDefault();}else if(!ev.shiftKey&&document.activeElement===a.at(-1)){a[0].focus();ev.preventDefault();}}});
function downloadJSON(value,name){const b=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function mutationPermission(act){const groups={events:['cancel-event'],tasks:['delete-task'],notices:['delete-notice'],attendance:['attendance-toggle'],people:[],plans:['register-car','new-car','car-menu','delete-car','copy-open','copy-apply','split-apply','merge-apply','leg-enabled','need-toggle','assign-choice','charge-edit','statement-lock','statement-reopen'],equipment:['stock'],training:['practice-defaults','practice-save','practice-draft-save','practice-edit','practice-copy','practice-history-add','practice-history-delete','practice-history-edit-toggle','menu-delete','category-add','category-edit','category-delete','category-save','category-edit-toggle','menu-reorder-toggle','menu-move','training-import']};for(const [k,acts]of Object.entries(groups))if(acts.includes(act))return edit(k);if(['role-edit','invite2','operator-transfer','operator-remove'].includes(act))return own();return true;}
function actHandled(ev){ev.preventDefault();ev.stopImmediatePropagation();}
async function switchGroup(gid){if(ctx.mode==='demo'){closeModal();return;}state=normalize(await api('/groups/'+gid+'/state'));ctx.base=clone(state);safeLocal('club-active-group',gid);practiceDraft=null;practiceEvent='';ui.attendanceEvent='';ui.attendanceMember='';ctx.conflict=null;closeModal();go('home');render();}
async function openDeepGroup(gid){const p=location.hash.slice(1).split('/');if(!gid)return;try{await switchGroup(gid);go(p.slice(2).join('/')||'home');}catch(err){toast(err.message);go('home');}}
async function refreshSession(){const r=await api('/session');ctx.user=r.user;ctx.csrf=r.csrf;ctx.groups=r.groups;}
async function showPendingInvite(){const token=sessionStorage.getItem('club-invite');if(ctx.mode!=='server'||!ctx.user||!ctx.base||!token)return;try{const info=await api('/invites/'+encodeURIComponent(token));modal('グループに参加',`<p style="margin-bottom:20px">${esc(info.groupName)}</p><form data-form="group-join"><input type="hidden" name="token" value="${esc(token)}"><button class="primary full">参加する</button></form>`);}catch(err){toast(err.message);}}
async function enablePush(){if(ctx.mode!=='server'){toast('デモでは通知送信しません');return;}if(!ctx.pushConfig.push){toast('送信サーバーの設定が必要です');return;}if(!('serviceWorker'in navigator)||!('PushManager'in window)){toast('ホーム画面から開いてください');return;}if(await Notification.requestPermission()!=='granted'){toast('通知は許可されていません');return;}const sw=await navigator.serviceWorker.ready;const str=ctx.pushConfig.vapidPublic.replace(/-/g,'+').replace(/_/g,'/'),bytes=Uint8Array.from(atob(str+'='.repeat((4-str.length%4)%4)),c=>c.charCodeAt(0));const sub=await sw.pushManager.getSubscription()||await sw.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});await api('/push/subscription','POST',{subscription:sub.toJSON()});toast('この端末を登録しました');}
document.addEventListener('click',async ev=>{
 const b=ev.target.closest('[data-act]');if(!b||b.disabled)return;const d=b.dataset,act=d.act,[r,id]=getRoute();
 if(ctx.busy){actHandled(ev);toast('保存中です');return;}
 if(ctx.ready&&ctx.base!==null&&!mutationPermission(act)){actHandled(ev);toast('編集権限がありません');return;}
 if(ctx.mode==='demo'&&!mutationPermission(act)){actHandled(ev);toast('編集権限がありません');return;}
 const carMutations=['register-car','new-car','delete-car','copy-apply','split-apply','merge-apply','leg-enabled','need-toggle','assign-choice'];
 if(carMutations.includes(act)&&plan(id)&&lockedPlan(id)){actHandled(ev);toast('先に月の確定を解除してください');return;}
 if(act==='task-toggle'){const t=state.tasks.find(t=>t.id===d.id);if(!edit('tasks')&&!ownTask(t)){actHandled(ev);toast('担当者ではありません');return;}t.completedAt=t.done?null:new Date().toISOString();t.completedBy=t.done?null:state.currentUser;return;}
 if(act==='role-edit'){if(!own()){actHandled(ev);return;}return;}
 const handled=new Set(['auth-tab','start-demo','group-picker','switch-group','logout2','invite2','operator-menu','operator-transfer','operator-remove','enable-push','reload-server','unsaved-export','backup-export','demo-reset2','calendar-image','calendar-image-render','batch-date-add','batch-date-remove','cancel-event','delete-task','delete-notice','practice-defaults','practice-event-pick','practice-event-set','practice-category','practice-select-menu','practice-next','practice-patterns','practice-pattern-save','practice-step','practice-order','practice-remove','practice-save','practice-draft-save','practice-preview','practice-image','practice-edit','practice-copy','practice-refresh','image-share','image-close','image-download','practice-history-add','practice-history-open','practice-history-download','practice-history-delete','practice-history-confirm-delete','practice-history-edit-toggle','category-add','category-edit','category-delete','category-save','category-edit-toggle','menu-reorder-toggle','menu-move','menu-delete','training-import','training-import-file','training-import-apply','settlement-month','settlement-detail2','charge-edit','statement-lock','statement-reopen','register-car']);
 if(!handled.has(act))return;actHandled(ev);
 try{
 switch(act){
 case'auth-tab':ctx.authTab=d.value;render();break;
 case'start-demo':ctx.mode='demo';ctx.user=null;ctx.base=null;state=normalize(JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')||demoSeed());ctx.ready=true;go('home');render();break;
 case'group-picker':if(ctx.mode==='demo'){modal('グループ',`<p>${esc(state.group.name)}</p><p class="note" style="margin-top:12px">端末内デモです。共有にはサーバー版を使用します。</p>`);}else{await refreshSession();modal('グループ',ctx.groups.map(g=>action('switch-group',esc(g.name),`data-id="${g.id}"`,'row')).join('')+`<hr class="rule"><form data-form="group-create">${field('グループ名','name','','text','required')}<button class="primary full">作成</button></form><form data-form="group-join" style="margin-top:24px">${field('招待コード','token','','text','required')}<button class="secondary full">参加</button></form>`);}break;
 case'switch-group':await switchGroup(d.id);break;
 case'logout2':await api('/logout','POST',{});ctx.user=null;ctx.base=null;ctx.csrf='';state=demoSeed();render();break;
 case'invite2':if(ctx.mode==='demo'){toast('招待はサーバー版で利用できます');break;}const inv=await api('/groups/'+state.group.id+'/invite','POST',{});modal('招待',`<p class="note">7日間有効・1回限り</p><textarea readonly aria-label="招待リンク" style="margin-top:12px">${esc(location.origin+'/?invite='+inv.token)}</textarea>`);break;
 case'operator-menu':if(!own())break;modal(oName(d.id),d.id===state.ownerId?'<p class="note">グループのオーナーです。</p>':action('operator-transfer','オーナーを移譲',`data-id="${d.id}"`,'row')+action('operator-remove','グループから外す',`data-id="${d.id}"`,'row danger-button'));break;
 case'operator-transfer':case'operator-remove':if(ctx.mode==='demo'){toast('サーバー版で利用できます');break;}if(!confirm(act==='operator-transfer'?'オーナーを移譲しますか？':'運営メンバーから外しますか？'))break;await api('/groups/'+state.group.id+'/membership','POST',{userId:d.id,action:act==='operator-transfer'?'transfer':'remove'});await switchGroup(state.group.id);break;
 case'enable-push':await enablePush();break;
 case'reload-server':await switchGroup(state.group.id);break;
 case'unsaved-export':downloadJSON(ctx.conflict?.state,'部活_未保存.json');break;
 case'backup-export':downloadJSON(state,'部活バックアップ_'+DEMO_TODAY+'.json');break;
 case'demo-reset2':if(confirm('デモの内容を初期状態に戻しますか？')){state=demoSeed();persist();practiceDraft=null;go('home');render();}break;
 case'calendar-image':modal('予定画像',`<p class="small" style="margin-bottom:18px">${ui.calendarYear}年${ui.calendarMonth+1}月</p><label class="option"><input type="checkbox" id="export-executive">幹部予定も含める</label><div class="form-actions">${action('calendar-image-render','プレビュー','','primary full')}</div>`);break;
 case'calendar-image-render':imagePreview(drawCalendar(!!document.getElementById('export-executive')?.checked),'予定表_'+ui.calendarYear+'-'+(ui.calendarMonth+1)+'.png');break;
 case'batch-date-add':{const value=document.getElementById('batch-date').value;if(!D.validDate(value))break;const list=document.getElementById('batch-dates');if(!list.querySelector(`[data-date="${value}"]`))list.insertAdjacentHTML('beforeend',action('batch-date-remove',esc(jpDate(value))+' ×',`data-date="${value}"`,'chip'));break;}
 case'batch-date-remove':b.remove();break;
 case'cancel-event':{const e=event(d.id);if(!confirm(e.cancelled?'予定の中止を取り消しますか？':'予定を中止しますか？出欠・配車の履歴は残ります。'))break;checkpoint();e.cancelled=!e.cancelled;persist();go('event/'+e.id);render();break;}
 case'delete-task':if(confirm('このやることを削除しますか？')){state.tasks=state.tasks.filter(t=>t.id!==d.id);persist();go('tasks');}break;
 case'delete-notice':if(confirm('このお知らせを削除しますか？')){state.notices=state.notices.filter(n=>n.id!==d.id);persist();go('notices');}break;
 case'practice-defaults':state=D.importLegacyTraining(state,LEGACY_DEFAULT).state;persist();render();break;
 case'practice-event-pick':modal('部活予定',action('practice-event-set','予定なし','data-id=""','row')+clubEvents().filter(e=>e.date>=D.addMonths(DEMO_TODAY,-1)&&e.date<=D.addMonths(DEMO_TODAY,3)).map(e=>action('practice-event-set',`<span class="row-main">${jpDate(e.date)} ${esc(eventVenue(e)?.name||e.title)}<span class="row-sub block">${e.start||'時刻なし'}</span></span>${icon('chev','chev')}`,`data-id="${e.id}"`,'row')).join(''));break;
 case'practice-event-set':practiceEvent=d.id;if(practiceDraft){practiceDraft.eventId=d.id;practiceDraft.context=sessionInfo(d.id);}closeModal();render();break;
 case'practice-category':practiceCategory=d.id;render();break;
 case'practice-select-menu':{const m=state.training.menus.find(m=>m.id===d.id),ix=practiceDraft.rows.findIndex(r=>r.menuId===d.id);if(ix>=0)practiceDraft.rows.splice(ix,1);else practiceDraft.rows.push({...clone(m),menuId:m.id,sets:Object.fromEntries(practiceDraft.patterns.map(p=>[p,1]))});render();break;}
 case'practice-next':if(!practiceDraft.title.trim())throw Error('表の名前を入力してください');if(!practiceDraft.rows.length)break;go('practice-sets');break;
 case'practice-patterns':modal('人数パターン',`<div class="options">${[1,2,3,4,5].map(p=>`<label class="option"><input type="checkbox" name="pattern" value="${p}" ${practiceDraft.patterns.includes(p)?'checked':''}>${p}人</label>`).join('')}</div><div class="form-actions">${action('practice-pattern-save','適用','','primary full')}</div>`);break;
 case'practice-pattern-save':{const pats=[...document.querySelectorAll('[name="pattern"]:checked')].map(x=>Number(x.value));D.trainingTotals(practiceDraft.rows,pats);practiceDraft.patterns=pats;practiceDraft.rows.forEach(r=>pats.forEach(p=>r.sets[p]??=1));closeModal();render();break;}
 case'practice-step':{const row=practiceDraft.rows[Number(d.index)],p=Number(d.pattern);row.sets[p]=Math.max(0,Math.min(999,(row.sets[p]||0)+Number(d.step)));render();break;}
 case'practice-order':{const i=Number(d.index),j=i+Number(d.step);if(j>=0&&j<practiceDraft.rows.length)[practiceDraft.rows[i],practiceDraft.rows[j]]=[practiceDraft.rows[j],practiceDraft.rows[i]];render();break;}
 case'practice-remove':practiceDraft.rows.splice(Number(d.index),1);if(!practiceDraft.rows.length)go('practice-select');else render();break;
 case'practice-save':case'practice-draft-save':{const saved=saveSheet(practiceDraft);if(act==='practice-save'){practiceDraft=null;go('practice-sheet/'+saved.id);}else toast('下書きを保存しました');break;}
 case'practice-edit':newPractice(d.id);break;
 case'practice-copy':{const s=state.training.sheets.find(x=>x.id===d.id);practiceDraft=clone(s);practiceDraft.id=UID();practiceDraft.title=s.title;practiceDraft.updatedAt=null;go('practice-select');break;}
 case'practice-refresh':practiceDraft.context=sessionInfo(practiceDraft.eventId);render();break;
 case'practice-preview':trainingImagePreview(practiceDraft);break;
 case'practice-image':trainingImagePreview(state.training.sheets.find(x=>x.id===d.id));break;
 case'image-share':if(previewCanvas)await shareCanvas(previewCanvas.cv,previewCanvas.name);break;
 case'image-close':closeModal();break;
 case'image-download':{if(!previewCanvas)break;downloadCanvas(previewCanvas.cv,previewCanvas.name);const add=document.getElementById('practice-history-on-save');if(add?.checked&&!previewPracticeHistorySaved&&previewPracticeSource){const snap=clone(previewPracticeSource),item={id:UID(),title:snap.title||'練習メニュー',createdAt:new Date().toISOString(),snapshot:snap};state.training.history.push(item);previewPracticeHistorySaved=true;persist();toast('画像を保存し、履歴に追加しました');}else toast('画像を保存しました');break;}
 case'practice-history-add':{if(!previewPracticeSource||previewPracticeHistorySaved)break;const snap=clone(previewPracticeSource),item={id:UID(),title:snap.title||'練習メニュー',createdAt:new Date().toISOString(),snapshot:snap};state.training.history.push(item);previewPracticeHistorySaved=true;persist();toast('履歴に追加しました');break;}
 case'practice-history-open':{const h=trainingHistoryItem(d.id);if(!h)throw Error('履歴が見つかりません');trainingImagePreview(h.snapshot,{allowHistory:false});break;}
 case'practice-history-download':{const h=trainingHistoryItem(d.id);if(!h)throw Error('履歴が見つかりません');downloadCanvas(drawTraining(h.snapshot),(h.title||'練習メニュー')+'.png');toast('画像を保存しました');break;}
 case'practice-history-delete':{const h=trainingHistoryItem(d.id);if(!h)break;modal('この履歴画像を削除しますか？',`<p class="note">削除した画像は元に戻せません。</p><div class="form-actions">${action('close-modal','キャンセル','','secondary full')}${action('practice-history-confirm-delete','削除',`data-id="${h.id}"`,'danger-button full')}</div>`);break;}
 case'practice-history-confirm-delete':{const h=trainingHistoryItem(d.id);if(!h)break;state.training.history=state.training.history.filter(x=>x.id!==h.id);persist();closeModal();render();toast('履歴を削除しました');break;}
 case'practice-history-edit-toggle':practiceHistoryEdit=!practiceHistoryEdit;render();break;
 case'category-add':modal('分類を追加',`<label class="field"><span class="label">分類名</span><input id="category-name" maxlength="80"></label>${action('category-save','追加','data-id=""','primary full')}`);break;
 case'category-edit':{const c=state.training.categories.find(c=>c.id===d.id);if(!c)break;modal('分類を編集',`<label class="field"><span class="label">分類名</span><input id="category-name" maxlength="80" value="${esc(c.name)}"></label>${action('category-save','保存',`data-id="${c.id}"`,'primary full')}`);break;}
 case'category-save':{const name=document.getElementById('category-name').value.trim(),cid=d.id;if(!name)throw Error('分類名を入力してください');if(state.training.categories.some(c=>c.id!==cid&&c.name===name))throw Error('同じ分類名があります');if(cid){const c=state.training.categories.find(c=>c.id===cid);if(!c)throw Error('分類が見つかりません');c.name=name;}else state.training.categories.push({id:UID(),name});persist();closeModal();render();break;}
 case'category-delete':{const c=state.training.categories.find(c=>c.id===d.id);if(!c)break;const used=state.training.menus.filter(m=>m.categoryId===c.id).length;if(used)throw Error('この分類にはメニューが登録されているため削除できません');checkpoint();state.training.categories=state.training.categories.filter(x=>x.id!==c.id);if(practiceCategory===c.id)practiceCategory='all';persist();render();toast(`「${c.name}」を削除しました`,true);break;}
 case'category-edit-toggle':practiceCategoryEdit=!practiceCategoryEdit;render();break;
 case'menu-reorder-toggle':practiceReorder=!practiceReorder;render();break;
 case'menu-move':{const m=state.training.menus.find(m=>m.id===d.id);if(!m)break;const sib=sortedTrainingMenus(state.training.menus.filter(x=>x.categoryId===m.categoryId)),i=sib.findIndex(x=>x.id===m.id),j=i+Number(d.step);if(j<0||j>=sib.length)break;[sib[i].order,sib[j].order]=[sib[j].order??j,sib[i].order??i];normalizeMenuOrders(m.categoryId);persist();render();break;}
 case'menu-delete':{const m=state.training.menus.find(m=>m.id===d.id),cat=m?.categoryId;if(!m)break;checkpoint();state.training.menus=state.training.menus.filter(x=>x.id!==m.id);if(cat)normalizeMenuOrders(cat);persist();if(getRoute()[0]==='menu-edit')go('menu-list');else render();toast(`「${m.name}」を削除しました`,true);break;}
 case'training-import':modal('以前のメニューを取り込む',`<p class="note">元データは削除しません。旧メニューアプリのJSONに対応します。</p><input type="file" accept="application/json,.json" id="training-import-file" style="margin-top:16px"><textarea id="training-json" aria-label="メニューJSON" style="margin-top:16px" placeholder="JSON"></textarea><div class="form-actions">${action('training-import-apply','取り込む','','primary full')}</div>`);break;
 case'training-import-apply':{const data=JSON.parse(document.getElementById('training-json').value),result=D.importLegacyTraining(state,data);state=result.state;persist();closeModal();render();toast(result.added+'種目を取り込みました');break;}
 case'settlement-month':ui.settlementMonth=D.addMonths(ui.settlementMonth+'-01',Number(d.dir)).slice(0,7);render();break;
 case'settlement-detail2':settlementDetail(d.rider,d.driver);break;
 case'charge-edit':chargeEdit(d.plan,d.leg,d.rider);break;
 case'statement-lock':if(confirm('実際の利用と金額を確認しましたか？この月の配車を確定します。')){const lines=settlementLines();if(!lines.length||lines.some(l=>l.unset))throw Error('単価を設定してください');state.settlements.push({id:UID(),month:ui.settlementMonth,locked:true,confirmedAt:new Date().toISOString(),confirmedBy:state.currentUser,revision:1+state.settlements.filter(x=>x.month===ui.settlementMonth).length,planIds:[...new Set(lines.flatMap(l=>l.details.map(x=>x.planId)))],lines:lines.map(l=>({...clone(l),riderName:pName(l.rider),driverName:pName(l.driver)}))});persist();render();}break;
 case'statement-reopen':if(confirm('この月の確定を解除しますか？再確定時に新しい記録を残します。')){currentStatement().locked=false;persist();render();}break;
 case'register-car':{const p=plan(d.id),errors=invalid(p);if(event(p.eventId).cancelled)errors.push('中止された予定です');if(errors.length){toast(errors[0]+'・下書きを保持');break;}checkpoint();p.status='registered';p.registeredAt=new Date().toISOString();p.registeredBy=state.currentUser;p.legDates||={outbound:event(p.eventId).date,return:event(p.eventId).endDate||event(p.eventId).date};persist();go('car-table/'+p.id);break;}
 }
 }catch(err){toast(err.message||'操作できませんでした');}
},true);
// Form edits don't rebuild while typing, avoiding focus loss on mobile.
document.addEventListener('input',ev=>{const el=ev.target;if(el.name==='practiceTitle'&&practiceDraft)practiceDraft.title=el.value;});
document.addEventListener('change',async ev=>{const el=ev.target;try{
 if(el.name==='kind'&&el.form?.dataset.form==='event2'){el.form.querySelector('[data-club-fields]').hidden=el.value!=='club';el.form.querySelector('[data-exec-fields]').hidden=el.value!=='executive';}
 if(el.name==='repeatMode')document.querySelectorAll('[data-repeat]').forEach(n=>n.hidden=n.dataset.repeat!==el.value);
 if(el.name==='targetMode')document.querySelectorAll('[data-target]').forEach(n=>n.hidden=n.dataset.target!==el.value);
 if(el.dataset.setIndex!==undefined){const v=Number(el.value);if(!Number.isInteger(v)||v<0||v>999){toast('0〜999で入力してください');render();return;}practiceDraft.rows[Number(el.dataset.setIndex)].sets[el.dataset.pattern]=v;render();}
 if(el.id==='training-import-file'&&el.files[0]){if(el.files[0].size>2000000)throw Error('2MB以下のJSONを選択してください');document.getElementById('training-json').value=await el.files[0].text();}
 }catch(err){toast(err.message);}});
const FORM_MODULE={task:'tasks',event:'events',event2:'events',notice:'notices',notice2:'notices',venue:'venues',equipment:'equipment',member:'people',menu:'training',charge:'plans','car-options2':'plans',role:'roles',group:'group',group2:'group',notifications:'settings',carsettings:'settings'};
document.addEventListener('submit',async ev=>{const f=ev.target;if(!f.dataset.form)return;const kind=f.dataset.form,key=FORM_MODULE[kind];if(ctx.busy){actHandled(ev);return;}if(key&&(key==='roles'||key==='group'||key==='settings'? !own():!edit(key))){actHandled(ev);toast('編集権限がありません');return;}
 const ours=['auth','group-create','group-join','group2','event2','notice2','menu','charge','car-options2','member'];if(!ours.includes(kind))return;actHandled(ev);const fd=new FormData(f),get=n=>String(fd.get(n)||'').trim(),id=f.dataset.id;
 try{
 switch(kind){
 case'auth':{const res=await api('/'+ctx.authTab,'POST',{email:get('email'),password:get('password'),name:get('name')});ctx.user=res.user;ctx.csrf=res.csrf;await refreshSession();ctx.base=null;if(ctx.groups.length){await switchGroup(localStorage.getItem('club-active-group')&&ctx.groups.some(g=>g.id===localStorage.getItem('club-active-group'))?localStorage.getItem('club-active-group'):ctx.groups[0].id);}else render();await showPendingInvite();break;}
 case'group-create':{const s=await api('/groups','POST',{name:get('name')});await refreshSession();state=normalize(s);ctx.base=clone(state);closeModal();go('home');render();break;}
 case'group-join':{let token=get('token');if(token.includes('?invite='))token=new URL(token).searchParams.get('invite');const res=await api('/join','POST',{token});sessionStorage.removeItem('club-invite');await refreshSession();await switchGroup(res.groupId);break;}
 case'group2':state.group.name=get('name');persist();go('settings');break;
 case'event2':{const old=event(id),start=get('start'),end=get('end'),date=get('date'),endDate=get('endDate');if(start&&!D.validTime(start)||end&&!D.validTime(end))throw Error('時刻を確認してください');if((!endDate||endDate===date)&&start&&end&&end<start)throw Error('終了時刻を確認してください');const mode=get('repeatMode')||'single';if(mode!=='single'&&endDate&&endDate!==date)throw Error('複数日予定と繰り返しは別に登録してください');const dates=D.datesFor({date,endDate,mode,repeatUntil:get('repeatUntil'),weekdays:fd.getAll('weekday').map(Number),selectedDates:[...f.querySelectorAll('#batch-dates [data-date]')].map(n=>n.dataset.date)});const ek=get('kind');const values={title:get('title'),date,start,end,endDate:endDate||date,kind:ek,venueId:ek==='club'?get('venue'):'',courts:get('courts')?Number(get('courts')):null,assignees:ek==='executive'?fd.getAll('assignee'):[],memo:get('memo'),notifications:fd.getAll('notify'),cancelled:old?.cancelled||false,assignmentNeedsReview:false};if(!values.title)throw Error('タイトルを入力してください');checkpoint();if(old)Object.assign(old,values);else{const series=dates.length>1?UID():null;for(const dt of dates)state.events.push({...clone(values),id:UID(),date:dt,endDate:mode==='single'?values.endDate:dt,seriesId:series});}D.seedAttendance(state);persist();go(old?'event/'+old.id:'calendar');break;}
 case'notice2':{const old=state.notices.find(n=>n.id===id),mode=get('targetMode'),n={id:id||UID(),title:get('title'),body:get('body'),targetMode:mode,assignmentNeedsReview:false,assignees:mode==='people'?fd.getAll('assignee'):[],targetRoles:mode==='role'?fd.getAll('targetRole'):[],notify:fd.has('push'),notifyVersion:(old?.notifyVersion||0)+(fd.has('push')?1:0),author:old?.author||oName(state.currentUser),authorId:old?.authorId||state.currentUser,date:old?.date||DEMO_TODAY};if(!n.title||!n.body)throw Error('タイトルと本文を入力してください');if(mode==='people'&&!n.assignees.length)throw Error('対象のメンバーを選択してください');if(mode==='role'&&!n.targetRoles.length)throw Error('対象の担当を選択してください');old?Object.assign(old,n):state.notices.unshift(n);persist();go('notices');break;}
 case'member':{const old=person(id),m={id:id||UID(),name:get('name'),grade:Number(get('grade')),seniority:get('seniority'),pickup:get('pickup'),memo:get('memo'),defaultOverride:get('defaultOverride')==='default'?null:get('defaultOverride')==='true',active:true,joinedDate:old?.joinedDate||DEMO_TODAY};if(!m.name)throw Error('名前を入力してください');old?Object.assign(old,m):state.people.push(m);D.seedAttendance(state);persist();go('members');break;}
 case'menu':{const minRaw=get('minutes'),secRaw=get('seconds'),mins=Number(minRaw||0),secs=Number(secRaw||0),name=get('name'),categoryId=get('categoryId');const nameErr=document.getElementById('menu-name-error'),catErr=document.getElementById('menu-category-error'),timeErr=document.getElementById('menu-time-error');if(nameErr)nameErr.textContent='';if(catErr)catErr.textContent='';if(timeErr)timeErr.textContent='';let bad=false;if(!name){if(nameErr)nameErr.textContent='名前を入力してください';bad=true;}if(!state.training.categories.some(c=>c.id===categoryId)){if(catErr)catErr.textContent='分類を選択してください';bad=true;}if(!Number.isInteger(mins)||mins<0||mins>1440||!Number.isInteger(secs)||secs<0||secs>59){if(timeErr)timeErr.textContent='分は0以上、秒は0〜59で入力してください';bad=true;}if(bad)break;const total=mins*60+secs,old=state.training.menus.find(m=>m.id===id),lastOrder=Math.max(-1,...state.training.menus.filter(m=>m.categoryId===categoryId).map(m=>Number(m.order??0))),m={id:id||UID(),name,categoryId,seconds:total,requiresSets:get('requiresSets')==='true',order:old?.order??lastOrder+1};old?Object.assign(old,m):state.training.menus.push(m);normalizeMenuOrders(m.categoryId);persist();go('menu-list');toast(old?'メニューを保存しました':'メニューを追加しました');break;}
 case'charge':{if(lockedPlan(id))throw Error('精算確定済みです');const p=plan(id),count=Number(get('count')),unit=get('unitYen')===''?null:Number(get('unitYen'));if(!Number.isInteger(count)||count<0||count>999||unit!==null&&(!Number.isInteger(unit)||unit<0))throw Error('回数と単価を確認してください');p.adjustments||={};p.adjustments[f.dataset.leg+'|'+f.dataset.rider]={count,unitYen:unit,excluded:fd.has('excluded'),reason:get('reason')};p.version++;persist();closeModal();render();break;}
 case'car-options2':{if(lockedPlan(id))throw Error('精算確定済みです');const p=plan(id);if(!D.validDate(get('outboundDate'))||!D.validDate(get('returnDate')))throw Error('利用日を確認してください');const unit=get('unitYen')===''?null:Number(get('unitYen'));if(unit!==null&&(!Number.isInteger(unit)||unit<0))throw Error('単価を確認してください');const legs=p.linked?['outbound','return']:fd.getAll('leg');if(!legs.length)throw Error('片道を1つ以上有効にしてください');p.enabled={outbound:legs.includes('outbound'),return:legs.includes('return')};p.legDates={outbound:get('outboundDate'),return:get('returnDate')};p.unitYen=unit;p.notifications=fd.getAll('notify');p.status='draft';p.version++;persist();closeModal();render();break;}
 }
 }catch(err){toast(err.message||'保存できませんでした');}
},true);
window.addEventListener('beforeunload',ev=>{if(ctx.busy){ev.preventDefault();ev.returnValue='';}});
window.addEventListener('offline',()=>{if(ctx.mode==='server'){ctx.conflict={message:'オフラインです。変更は保存できません。'};render();}});
window.addEventListener('online',()=>{if(ctx.mode==='server'&&ctx.base)toast('接続が戻りました。再読込してください');});
async function bootstrap(){
 const url=new URL(location.href);if(url.searchParams.get('invite'))sessionStorage.setItem('club-invite',url.searchParams.get('invite'));
 if(location.protocol==='file:'||url.searchParams.has('demo')){ctx.mode='demo';let saved;try{saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{}state=normalize(saved?.schema===2?saved:demoSeed());ctx.ready=true;render();return;}
 try{ctx.pushConfig=await api('/config');ctx.mode='server';if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});try{await refreshSession();if(ctx.groups.length){const active=localStorage.getItem('club-active-group'),gid=ctx.groups.some(g=>g.id===active)?active:ctx.groups[0].id;state=normalize(await api('/groups/'+gid+'/state'));ctx.base=clone(state);}}catch(err){if(err.status!==401)throw err;}ctx.ready=true;render();await showPendingInvite();}
 catch(err){ctx.ready=true;ctx.mode='server';ctx.user=null;ctx.base=null;render();toast('サーバーに接続できません。接続を確認してください');}
}
async function refreshWhenIdle(){
 if(ctx.mode!=='server'||!ctx.base||ctx.busy||ctx.conflict||document.hidden||document.querySelector('form,.modal')||drag?.active||ui.selectedPerson||practiceDraft)return;
 try{const gid=state.group.id,fresh=await api('/groups/'+gid+'/state');if(ctx.busy||ctx.conflict||document.querySelector('form,.modal')||drag?.active||ui.selectedPerson||practiceDraft||state.group.id!==gid)return;if(fresh.version>ctx.base.version){state=normalize(fresh);ctx.base=clone(state);undoState=null;render();}}
 catch(err){if(err.status===401||err.status===403){ctx.conflict={message:'ログインまたはグループへのアクセスを確認してください'};render();}}
}
setInterval(refreshWhenIdle,30000);window.addEventListener('focus',refreshWhenIdle);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshWhenIdle();});
window.ClubApp={state:()=>clone(state),context:()=>({...ctx,user:ctx.user?{id:ctx.user.id}:null,csrf:undefined}),reset:()=>{if(ctx.mode!=='demo')throw Error('demo only');state=demoSeed();persist();render();},render,domain:D,drawTraining,drawCalendar,drawCarCanvas,newPractice,saveSheet,moveMember,copyPlan,addPlan,getPractice:()=>practiceDraft,settlement:()=>settlementLines(),setState:s=>{if(ctx.mode!=='demo')throw Error('demo only');state=normalize(clone(s));persist();render();}};
// Application startup is owned by workflow.js (v0.9).
